/* eslint-disable */
/**
 * GENERIERT — nicht von Hand aendern.
 * Quelle: scripts/price-audit.mjs · `node scripts/price-audit.mjs`
 *
 * Das vollstaendige Inventar der Preisliterale im Quelltext: jede Zahl, die
 * an einem Waehrungszeichen steht und damit im Code entschieden wurde statt
 * in der Datenbank. Nicht enthalten ist die Formatierung von Laufzeitwerten
 * (`toFixed`, `toLocaleString`, `Intl.NumberFormat`) — dort gibt es nichts
 * zu entscheiden.
 *
 * Diese Datei ist ein BERICHT, kein Modul mit Geschaeftslogik. Sie aendert
 * keinen einzigen Preis und wird von keinem Produktivpfad gelesen.
 */

export interface PreisTreffer {
  /** 1-basierte Zeilennummer zum Stand der letzten Generierung. */
  zeile: number
  /** Die gefundenen Literale, so wie sie im Quelltext stehen. */
  literale: string[]
  /** Steht in einem Kommentar — Dokumentation, keine Zusage an Nutzer. */
  kommentar: boolean
  /** Zeile mischt Literal und Formatierung eines Laufzeitwertes. */
  dynamisch: boolean
}

export type PreisBereich =
  /** Unter src/app/(public) — jeder anonyme Besucher sieht das. */
  | 'oeffentlich'
  /** src/lib/seo-data — Fliesstext der SEO-Seiten, ebenfalls oeffentlich. */
  | 'redaktionell'
  /** Erst nach Anmeldung sichtbar. */
  | 'angemeldet'
  /** Admin- und Investor-Bereich. */
  | 'intern'
  /** API-Antworten. */
  | 'api'
  /** Bibliotheken und Komponenten, je nach Aufrufer. */
  | 'geteilt'
  /** Tests und Fixtures — nie ausgeliefert. */
  | 'test'

export interface PreisDatei {
  datei: string
  bereich: PreisBereich
  treffer: PreisTreffer[]
}

/** Stand der Generierung: 2026-09-12 */
export const PREIS_AUDIT_STAND = '2026-09-12' as const

export const PREIS_AUDIT: readonly PreisDatei[] = [
  {
    datei: "src/lib/seo-data/magazin.ts",
    bereich: "redaktionell",
    treffer: [
      { zeile: 15, literale: ["80-150 €"], kommentar: true, dynamisch: false },
      { zeile: 16, literale: ["200-400 €"], kommentar: true, dynamisch: false },
      { zeile: 18, literale: ["45 €"], kommentar: true, dynamisch: false },
      { zeile: 19, literale: ["60 €","240 €"], kommentar: true, dynamisch: false },
      { zeile: 61, literale: ["40-70 €","90 €"], kommentar: false, dynamisch: false },
      { zeile: 63, literale: ["80-150 €","200-400 €","250-500 €"], kommentar: false, dynamisch: false },
      { zeile: 68, literale: ["50 €"], kommentar: false, dynamisch: false },
      { zeile: 86, literale: ["15-30 €"], kommentar: false, dynamisch: false },
      { zeile: 107, literale: ["45 €"], kommentar: false, dynamisch: false },
      { zeile: 108, literale: ["60 €","240 €"], kommentar: false, dynamisch: false },
      { zeile: 109, literale: ["25 €"], kommentar: false, dynamisch: false },
      { zeile: 110, literale: ["170 €"], kommentar: false, dynamisch: false },
      { zeile: 112, literale: ["3.000 €","1.800-2.400 €"], kommentar: false, dynamisch: false },
      { zeile: 120, literale: ["10.000 €"], kommentar: false, dynamisch: false },
      { zeile: 121, literale: ["24.500 €"], kommentar: false, dynamisch: false },
      { zeile: 122, literale: ["22.000 €"], kommentar: false, dynamisch: false },
      { zeile: 123, literale: ["400-800 €"], kommentar: false, dynamisch: false },
      { zeile: 159, literale: ["22.000 €","50.000 €"], kommentar: false, dynamisch: false },
      { zeile: 161, literale: ["60-100 €","1000 €"], kommentar: false, dynamisch: false },
      { zeile: 172, literale: ["24.500 €"], kommentar: false, dynamisch: false },
      { zeile: 181, literale: ["10.908 €"], kommentar: false, dynamisch: false },
      { zeile: 182, literale: ["10.909 €","15.999 €"], kommentar: false, dynamisch: false },
      { zeile: 183, literale: ["16.000 €","62.809 €"], kommentar: false, dynamisch: false },
      { zeile: 184, literale: ["277.000 €"], kommentar: false, dynamisch: false },
      { zeile: 190, literale: ["22.000 €","50.000 €"], kommentar: false, dynamisch: false },
      { zeile: 194, literale: ["24.500 €"], kommentar: false, dynamisch: false },
      { zeile: 196, literale: ["24.500 €"], kommentar: false, dynamisch: false },
      { zeile: 198, literale: ["200-400 €"], kommentar: false, dynamisch: false },
      { zeile: 204, literale: ["420 €","250 €"], kommentar: false, dynamisch: false },
      { zeile: 207, literale: ["15-30 €"], kommentar: false, dynamisch: false },
      { zeile: 215, literale: ["60 €","47.520 €"], kommentar: false, dynamisch: false },
      { zeile: 216, literale: ["45 €","8.910 €"], kommentar: false, dynamisch: false },
      { zeile: 217, literale: ["3.500 €"], kommentar: false, dynamisch: false },
      { zeile: 218, literale: ["800 €"], kommentar: false, dynamisch: false },
      { zeile: 219, literale: ["600 €"], kommentar: false, dynamisch: false },
      { zeile: 220, literale: ["1.200 €"], kommentar: false, dynamisch: false },
      { zeile: 221, literale: ["32.510 €"], kommentar: false, dynamisch: false },
      { zeile: 222, literale: ["5.400 €"], kommentar: false, dynamisch: false },
      { zeile: 223, literale: ["5.800 €"], kommentar: false, dynamisch: false },
      { zeile: 224, literale: ["1.450 €"], kommentar: false, dynamisch: false },
      { zeile: 225, literale: ["19.860 €"], kommentar: false, dynamisch: false },
      { zeile: 226, literale: ["1.655 €"], kommentar: false, dynamisch: false },
      { zeile: 234, literale: ["15-30 €"], kommentar: false, dynamisch: false },
      { zeile: 237, literale: ["60-100 €"], kommentar: false, dynamisch: false },
      { zeile: 377, literale: ["15-30 €"], kommentar: false, dynamisch: false },
      { zeile: 378, literale: ["150 €","400-600 €"], kommentar: false, dynamisch: false },
      { zeile: 387, literale: ["8.500 €"], kommentar: false, dynamisch: false },
      { zeile: 389, literale: ["4.200 €"], kommentar: false, dynamisch: false },
      { zeile: 391, literale: ["2.800 €"], kommentar: false, dynamisch: false },
      { zeile: 397, literale: ["15-30 €"], kommentar: false, dynamisch: false },
      { zeile: 407, literale: ["22 €","18 €","16 €","20 €"], kommentar: false, dynamisch: false },
      { zeile: 409, literale: ["150-600 €"], kommentar: false, dynamisch: false },
      { zeile: 417, literale: ["250-800 €"], kommentar: false, dynamisch: false },
      { zeile: 421, literale: ["420 €"], kommentar: false, dynamisch: false },
      { zeile: 422, literale: ["840 €"], kommentar: false, dynamisch: false },
      { zeile: 427, literale: ["250-400 €"], kommentar: false, dynamisch: false },
      { zeile: 428, literale: ["800-1.200 €"], kommentar: false, dynamisch: false },
      { zeile: 433, literale: ["40-120 €"], kommentar: false, dynamisch: false },
      { zeile: 437, literale: ["1.500-2.500 €"], kommentar: false, dynamisch: false },
      { zeile: 450, literale: ["85-1.380 €"], kommentar: false, dynamisch: false },
      { zeile: 454, literale: ["200-400 €"], kommentar: false, dynamisch: false },
      { zeile: 458, literale: ["8-15 €"], kommentar: false, dynamisch: false },
      { zeile: 459, literale: ["20-40 €"], kommentar: false, dynamisch: false },
      { zeile: 460, literale: ["25-40 €"], kommentar: false, dynamisch: false },
      { zeile: 482, literale: ["15-30 €"], kommentar: false, dynamisch: false },
      { zeile: 483, literale: ["12-50 €"], kommentar: false, dynamisch: false },
      { zeile: 484, literale: ["250-800 €"], kommentar: false, dynamisch: false },
      { zeile: 485, literale: ["40-120 €"], kommentar: false, dynamisch: false },
      { zeile: 486, literale: ["200-400 €"], kommentar: false, dynamisch: false },
      { zeile: 487, literale: ["8-15 €"], kommentar: false, dynamisch: false },
      { zeile: 488, literale: ["25-40 €"], kommentar: false, dynamisch: false },
      { zeile: 492, literale: ["500-900 €","80-200 €"], kommentar: false, dynamisch: false },
      { zeile: 494, literale: ["100-150 €"], kommentar: false, dynamisch: false },
      { zeile: 560, literale: ["15 €"], kommentar: false, dynamisch: false },
      { zeile: 578, literale: ["250-500 €"], kommentar: false, dynamisch: false },
      { zeile: 580, literale: ["800-1.500 €"], kommentar: false, dynamisch: false },
      { zeile: 590, literale: ["500-2.000 €"], kommentar: false, dynamisch: false },
      { zeile: 612, literale: ["100-300 €"], kommentar: false, dynamisch: false },
      { zeile: 662, literale: ["10-40 €","16-39 €","9-43 €","19-69 €"], kommentar: false, dynamisch: false },
      { zeile: 677, literale: ["800.000 €","80.000 €"], kommentar: false, dynamisch: false },
      { zeile: 713, literale: ["5 €","1.260 €"], kommentar: false, dynamisch: false },
      { zeile: 719, literale: ["15,90 €"], kommentar: false, dynamisch: false },
      { zeile: 728, literale: ["19,90 €"], kommentar: false, dynamisch: false },
      { zeile: 742, literale: ["20 €"], kommentar: false, dynamisch: false },
      { zeile: 784, literale: ["800 €"], kommentar: false, dynamisch: false },
      { zeile: 786, literale: ["800 €"], kommentar: false, dynamisch: false },
      { zeile: 795, literale: ["60-150 €","15-20 €"], kommentar: false, dynamisch: false },
      { zeile: 797, literale: ["1.000-3.000 €"], kommentar: false, dynamisch: false },
      { zeile: 804, literale: ["20 €"], kommentar: false, dynamisch: false },
      { zeile: 817, literale: ["22-32 €","35-55 €","40-70 €","16-25 €"], kommentar: false, dynamisch: false },
      { zeile: 834, literale: ["450 €"], kommentar: false, dynamisch: false },
      { zeile: 835, literale: ["250 €"], kommentar: false, dynamisch: false },
      { zeile: 836, literale: ["200 €"], kommentar: false, dynamisch: false },
      { zeile: 837, literale: ["80 €"], kommentar: false, dynamisch: false },
      { zeile: 838, literale: ["100 €"], kommentar: false, dynamisch: false },
      { zeile: 839, literale: ["100 €"], kommentar: false, dynamisch: false },
      { zeile: 840, literale: ["1.800 €"], kommentar: false, dynamisch: false },
      { zeile: 841, literale: ["800 €"], kommentar: false, dynamisch: false },
      { zeile: 842, literale: ["250 €"], kommentar: false, dynamisch: false },
      { zeile: 843, literale: ["4.030 €"], kommentar: false, dynamisch: false },
      { zeile: 846, literale: ["45 €","810 €"], kommentar: false, dynamisch: false },
      { zeile: 847, literale: ["4.840 €"], kommentar: false, dynamisch: false },
      { zeile: 854, literale: ["4.840 €","38 €"], kommentar: false, dynamisch: false },
      { zeile: 857, literale: ["50 €"], kommentar: false, dynamisch: false },
      { zeile: 874, literale: ["65 €","35 €","85 €","140 €"], kommentar: false, dynamisch: false },
      { zeile: 875, literale: ["48 €","28 €","65 €","95 €"], kommentar: false, dynamisch: false },
      { zeile: 876, literale: ["35 €","22 €","55 €","70 €"], kommentar: false, dynamisch: false },
      { zeile: 877, literale: ["49 €","28 €","68 €","102 €"], kommentar: false, dynamisch: false },
      { zeile: 897, literale: ["50 €","50 €"], kommentar: false, dynamisch: false },
      { zeile: 898, literale: ["3 €"], kommentar: false, dynamisch: false },
      { zeile: 899, literale: ["0,60 €"], kommentar: false, dynamisch: false },
      { zeile: 900, literale: ["54 €"], kommentar: false, dynamisch: false },
      { zeile: 902, literale: ["48 €"], kommentar: false, dynamisch: false },
      { zeile: 906, literale: ["50 €","125 €"], kommentar: false, dynamisch: false },
      { zeile: 907, literale: ["15 €"], kommentar: false, dynamisch: false },
      { zeile: 908, literale: ["3 €"], kommentar: false, dynamisch: false },
      { zeile: 909, literale: ["143 €"], kommentar: false, dynamisch: false },
      { zeile: 911, literale: ["68 €"], kommentar: false, dynamisch: false },
      { zeile: 915, literale: ["50 €","125 €"], kommentar: false, dynamisch: false },
      { zeile: 916, literale: ["30 €"], kommentar: false, dynamisch: false },
      { zeile: 917, literale: ["155 €"], kommentar: false, dynamisch: false },
      { zeile: 921, literale: ["68 €","125 €"], kommentar: false, dynamisch: false },
      { zeile: 924, literale: ["130-200 €"], kommentar: false, dynamisch: false },
      { zeile: 934, literale: ["86 €"], kommentar: false, dynamisch: false },
      { zeile: 935, literale: ["79 €"], kommentar: false, dynamisch: false },
      { zeile: 936, literale: ["79 €","48 €"], kommentar: false, dynamisch: false },
      { zeile: 941, literale: ["73 €"], kommentar: false, dynamisch: false },
      { zeile: 942, literale: ["65 €"], kommentar: false, dynamisch: false },
      { zeile: 948, literale: ["95 €","130 €"], kommentar: false, dynamisch: false },
      { zeile: 949, literale: ["250-500 €"], kommentar: false, dynamisch: false },
      { zeile: 1003, literale: ["800-1.500 €","45-85 €","19.000-36.000 €"], kommentar: false, dynamisch: false },
      { zeile: 1008, literale: ["25.000 €"], kommentar: false, dynamisch: false },
      { zeile: 1013, literale: ["5 €"], kommentar: false, dynamisch: false },
      { zeile: 1014, literale: ["12 €"], kommentar: false, dynamisch: false },
      { zeile: 1017, literale: ["250-400 €"], kommentar: false, dynamisch: false },
      { zeile: 1019, literale: ["250-400 €","800-1.500 €"], kommentar: false, dynamisch: false },
      { zeile: 1025, literale: ["2.200 €"], kommentar: false, dynamisch: false },
      { zeile: 1029, literale: ["8.500 €"], kommentar: false, dynamisch: false },
      { zeile: 1030, literale: ["4.800 €"], kommentar: false, dynamisch: false },
      { zeile: 1031, literale: ["3.700 €"], kommentar: false, dynamisch: false },
      { zeile: 1033, literale: ["75 €","1.350 €"], kommentar: false, dynamisch: false },
      { zeile: 1034, literale: ["8.500 €"], kommentar: false, dynamisch: false },
      { zeile: 1035, literale: ["1.350 €","2.700 €"], kommentar: false, dynamisch: false },
      { zeile: 1036, literale: ["4.800 €"], kommentar: false, dynamisch: false },
      { zeile: 1037, literale: ["100 €"], kommentar: false, dynamisch: false },
      { zeile: 1038, literale: ["6.300 €"], kommentar: false, dynamisch: false },
      { zeile: 1040, literale: ["31.200 €"], kommentar: false, dynamisch: false },
      { zeile: 1092, literale: ["35-55 €"], kommentar: false, dynamisch: false },
      { zeile: 1093, literale: ["45-70 €"], kommentar: false, dynamisch: false },
      { zeile: 1094, literale: ["65-95 €"], kommentar: false, dynamisch: false },
      { zeile: 1095, literale: ["80-120 €"], kommentar: false, dynamisch: false },
      { zeile: 1137, literale: ["24.500 €"], kommentar: false, dynamisch: false },
      { zeile: 1166, literale: ["800-1.500 €"], kommentar: false, dynamisch: false },
      { zeile: 1180, literale: ["50-100 €","150-250 €","200-400 €","2.500-4.500 €"], kommentar: false, dynamisch: false },
      { zeile: 1209, literale: ["60 €"], kommentar: false, dynamisch: false },
      { zeile: 1210, literale: ["30 €"], kommentar: false, dynamisch: false },
      { zeile: 1211, literale: ["90 €"], kommentar: false, dynamisch: false },
      { zeile: 1228, literale: ["15 €"], kommentar: false, dynamisch: false },
      { zeile: 1229, literale: ["15 €"], kommentar: false, dynamisch: false },
      { zeile: 1230, literale: ["30 €"], kommentar: false, dynamisch: false },
      { zeile: 1231, literale: ["60 €"], kommentar: false, dynamisch: false },
      { zeile: 1247, literale: ["60 €"], kommentar: false, dynamisch: false },
      { zeile: 1258, literale: ["500-2.000 €"], kommentar: false, dynamisch: false },
      { zeile: 1263, literale: ["800 €"], kommentar: false, dynamisch: false },
      { zeile: 1264, literale: ["60 €"], kommentar: false, dynamisch: false },
      { zeile: 1265, literale: ["860 €"], kommentar: false, dynamisch: false },
      { zeile: 1280, literale: ["60 €"], kommentar: false, dynamisch: false },
      { zeile: 1289, literale: ["30 €","120 €"], kommentar: false, dynamisch: false },
      { zeile: 1296, literale: ["120 €"], kommentar: false, dynamisch: false },
      { zeile: 1297, literale: ["100 €"], kommentar: false, dynamisch: false },
      { zeile: 1298, literale: ["60 €"], kommentar: false, dynamisch: false },
      { zeile: 1299, literale: ["280 €"], kommentar: false, dynamisch: false },
      { zeile: 1308, literale: ["30 €","50-60 €"], kommentar: false, dynamisch: false },
      { zeile: 1309, literale: ["30 €"], kommentar: false, dynamisch: false },
      { zeile: 1314, literale: ["350 €"], kommentar: false, dynamisch: false },
      { zeile: 1324, literale: ["175 €"], kommentar: false, dynamisch: false },
      { zeile: 1325, literale: ["800-1.500 €"], kommentar: false, dynamisch: false },
      { zeile: 1329, literale: ["1.200 €"], kommentar: false, dynamisch: false },
      { zeile: 1330, literale: ["150 €"], kommentar: false, dynamisch: false },
      { zeile: 1331, literale: ["250 €"], kommentar: false, dynamisch: false },
      { zeile: 1332, literale: ["60 €"], kommentar: false, dynamisch: false },
      { zeile: 1333, literale: ["1.660 €"], kommentar: false, dynamisch: false },
      { zeile: 1348, literale: ["400 €"], kommentar: false, dynamisch: false },
      { zeile: 1363, literale: ["400 €"], kommentar: false, dynamisch: false },
      { zeile: 1371, literale: ["900 €"], kommentar: false, dynamisch: false },
      { zeile: 1372, literale: ["600 €"], kommentar: false, dynamisch: false },
      { zeile: 1373, literale: ["800 €"], kommentar: false, dynamisch: false },
      { zeile: 1374, literale: ["2.400 €"], kommentar: false, dynamisch: false },
      { zeile: 1375, literale: ["1.200 €"], kommentar: false, dynamisch: false },
      { zeile: 1376, literale: ["250 €"], kommentar: false, dynamisch: false },
      { zeile: 1377, literale: ["6.150 €"], kommentar: false, dynamisch: false },
      { zeile: 1379, literale: ["512 €"], kommentar: false, dynamisch: false },
      { zeile: 1381, literale: ["60 €"], kommentar: false, dynamisch: false },
      { zeile: 1398, literale: ["6.000 €"], kommentar: false, dynamisch: false },
      { zeile: 1467, literale: ["200-500 €"], kommentar: false, dynamisch: false },
      { zeile: 1477, literale: ["800-1.500 €"], kommentar: false, dynamisch: false },
      { zeile: 1578, literale: ["2.500-5.000 €","30.000-80.000 €","20-60 €","150-300 €"], kommentar: false, dynamisch: false },
      { zeile: 1579, literale: ["660 €","330 €"], kommentar: false, dynamisch: false },
      { zeile: 1580, literale: ["25.000 €"], kommentar: false, dynamisch: false },
      { zeile: 1594, literale: ["4.000-9.000 €"], kommentar: false, dynamisch: false },
      { zeile: 1595, literale: ["3.000-4.500 €"], kommentar: false, dynamisch: false },
      { zeile: 1596, literale: ["300-500 €"], kommentar: false, dynamisch: false },
      { zeile: 1597, literale: ["200-500 €"], kommentar: false, dynamisch: false },
      { zeile: 1607, literale: ["150-300 €","120-300 €"], kommentar: false, dynamisch: false },
      { zeile: 1608, literale: ["20-60 €"], kommentar: false, dynamisch: false },
      { zeile: 1610, literale: ["150 €"], kommentar: false, dynamisch: false },
      { zeile: 1617, literale: ["250 €","500-900 €"], kommentar: false, dynamisch: false },
      { zeile: 1618, literale: ["300 €"], kommentar: false, dynamisch: false },
      { zeile: 1620, literale: ["660 €","330 €"], kommentar: false, dynamisch: false },
      { zeile: 1624, literale: ["12.350 €"], kommentar: false, dynamisch: false },
      { zeile: 1625, literale: ["25.000 €","100.000 €"], kommentar: false, dynamisch: false },
      { zeile: 1626, literale: ["24.500 €"], kommentar: false, dynamisch: false },
      { zeile: 1635, literale: ["200-350 €"], kommentar: false, dynamisch: false },
      { zeile: 1636, literale: ["1.200-2.500 €"], kommentar: false, dynamisch: false },
      { zeile: 1637, literale: ["400-800 €"], kommentar: false, dynamisch: false },
      { zeile: 1638, literale: ["180-360 €"], kommentar: false, dynamisch: false },
      { zeile: 1639, literale: ["800-1.000 €"], kommentar: false, dynamisch: false },
      { zeile: 1640, literale: ["150-400 €"], kommentar: false, dynamisch: false },
      { zeile: 1641, literale: ["190-250 €"], kommentar: false, dynamisch: false },
      { zeile: 1642, literale: ["3.100-5.700 €"], kommentar: false, dynamisch: false },
      { zeile: 1644, literale: ["5.000-7.000 €"], kommentar: false, dynamisch: false },
      { zeile: 1667, literale: ["3.000-6.000 €"], kommentar: false, dynamisch: false },
      { zeile: 1679, literale: ["30.000-80.000 €","3.500-7.000 €"], kommentar: false, dynamisch: false },
      { zeile: 1681, literale: ["30.000-80.000 €"], kommentar: false, dynamisch: false },
      { zeile: 1693, literale: ["0-1.000 €","6.000-15.000 €"], kommentar: false, dynamisch: false },
      { zeile: 1694, literale: ["0 €","10.000-30.000 €"], kommentar: false, dynamisch: false },
      { zeile: 1695, literale: ["0 €","8.000-25.000 €"], kommentar: false, dynamisch: false },
      { zeile: 1696, literale: ["1.200-2.500 €","1.200-2.500 €"], kommentar: false, dynamisch: false },
      { zeile: 1697, literale: ["400-800 €","2.000-5.000 €"], kommentar: false, dynamisch: false },
      { zeile: 1698, literale: ["500-800 €","1.500-3.000 €"], kommentar: false, dynamisch: false },
      { zeile: 1699, literale: ["150-400 €","2.000-5.000 €"], kommentar: false, dynamisch: false },
      { zeile: 1700, literale: ["2.300-5.500 €","30.700-85.500 €"], kommentar: false, dynamisch: false },
      { zeile: 1708, literale: ["810 €","45 €","1.800-3.000 €"], kommentar: false, dynamisch: false },
      { zeile: 1709, literale: ["400-700 €"], kommentar: false, dynamisch: false },
      { zeile: 1710, literale: ["30-50 €","150-300 €"], kommentar: false, dynamisch: false },
      { zeile: 1711, literale: ["50.000 €","0 €","650 €"], kommentar: false, dynamisch: false },
      { zeile: 1712, literale: ["20-40 €","80-150 €"], kommentar: false, dynamisch: false },
      { zeile: 1713, literale: ["0 €","200-400 €"], kommentar: false, dynamisch: false },
      { zeile: 1714, literale: ["100-200 €","300-600 €"], kommentar: false, dynamisch: false },
      { zeile: 1715, literale: ["960-1.100 €","3.580-5.800 €"], kommentar: false, dynamisch: false },
      { zeile: 1717, literale: ["3.500-5.800 €"], kommentar: false, dynamisch: false },
      { zeile: 1721, literale: ["60 €"], kommentar: false, dynamisch: false },
      { zeile: 1723, literale: ["1.030 €","51 €"], kommentar: false, dynamisch: false },
      { zeile: 1725, literale: ["4.700 €","51 €","3.500-4.500 €"], kommentar: false, dynamisch: false },
      { zeile: 1731, literale: ["2.300-5.500 €","30.000-85.000 €"], kommentar: false, dynamisch: false },
      { zeile: 1749, literale: ["30.000 €"], kommentar: false, dynamisch: false },
      { zeile: 1755, literale: ["500-1.000 €"], kommentar: false, dynamisch: false },
      { zeile: 1839, literale: ["3.000 €","50.000-70.000 €"], kommentar: false, dynamisch: false },
      { zeile: 1878, literale: ["25-90 €","25 €","35-65 €","90 €","40-55 €"], kommentar: false, dynamisch: false },
      { zeile: 1879, literale: ["500-1.500 €"], kommentar: false, dynamisch: false },
      { zeile: 1880, literale: ["3.000 €"], kommentar: false, dynamisch: false },
      { zeile: 1887, literale: ["25 bis 90 €","500 bis 1.500 €"], kommentar: false, dynamisch: false },
      { zeile: 1897, literale: ["25-50 €","38 €"], kommentar: false, dynamisch: false },
      { zeile: 1898, literale: ["40-65 €","50 €"], kommentar: false, dynamisch: false },
      { zeile: 1899, literale: ["55-90 €","70 €"], kommentar: false, dynamisch: false },
      { zeile: 1900, literale: ["35-60 €","45 €"], kommentar: false, dynamisch: false },
      { zeile: 1901, literale: ["45-75 €","58 €"], kommentar: false, dynamisch: false },
      { zeile: 1902, literale: ["25-45 €","32 €"], kommentar: false, dynamisch: false },
      { zeile: 1907, literale: ["20-35 €"], kommentar: false, dynamisch: false },
      { zeile: 1908, literale: ["15-25 €"], kommentar: false, dynamisch: false },
      { zeile: 1916, literale: ["45 €","45 €"], kommentar: false, dynamisch: false },
      { zeile: 1917, literale: ["180-200 €","36-40 €"], kommentar: false, dynamisch: false },
      { zeile: 1918, literale: ["700-850 €","32-39 €"], kommentar: false, dynamisch: false },
      { zeile: 1932, literale: ["4.000 €","800 €","1.200-2.000 €"], kommentar: false, dynamisch: false },
      { zeile: 1936, literale: ["2.500-3.000 €","4.000 €","1.600 €"], kommentar: false, dynamisch: false },
      { zeile: 1956, literale: ["50-150 €"], kommentar: false, dynamisch: false },
      { zeile: 1957, literale: ["30-60 €"], kommentar: false, dynamisch: false },
      { zeile: 1985, literale: ["50-150 €"], kommentar: false, dynamisch: false },
      { zeile: 1993, literale: ["35 €","45 €"], kommentar: false, dynamisch: false },
      { zeile: 1994, literale: ["5 €"], kommentar: false, dynamisch: false },
      { zeile: 1998, literale: ["55 €","10 €","45 €"], kommentar: false, dynamisch: false },
      { zeile: 2002, literale: ["32 €","45 €"], kommentar: false, dynamisch: false },
      { zeile: 2003, literale: ["38 €","45 €"], kommentar: false, dynamisch: false },
      { zeile: 2004, literale: ["45 €","45 €"], kommentar: false, dynamisch: false },
      { zeile: 2005, literale: ["58 €","45 €"], kommentar: false, dynamisch: false },
      { zeile: 2006, literale: ["70 €","45 €"], kommentar: false, dynamisch: false },
      { zeile: 2008, literale: ["110 bis 150 €","70-90 €"], kommentar: false, dynamisch: false },
      { zeile: 2014, literale: ["25 €","90 €","500-1.500 €"], kommentar: false, dynamisch: false },
      { zeile: 2028, literale: ["3.000-8.000 €","20.000-50.000 €"], kommentar: false, dynamisch: false },
      { zeile: 2029, literale: ["20-45 €","300-700 €","900 €"], kommentar: false, dynamisch: false },
      { zeile: 2030, literale: ["2.500-4.500 €","1.600-2.800 €"], kommentar: false, dynamisch: false },
      { zeile: 2055, literale: ["1.500-3.500 €"], kommentar: false, dynamisch: false },
      { zeile: 2063, literale: ["50-200 €"], kommentar: false, dynamisch: false },
      { zeile: 2064, literale: ["20-60 €"], kommentar: false, dynamisch: false },
      { zeile: 2066, literale: ["150 €"], kommentar: false, dynamisch: false },
      { zeile: 2069, literale: ["150-300 €"], kommentar: false, dynamisch: false },
      { zeile: 2087, literale: ["20.000-50.000 €"], kommentar: false, dynamisch: false },
      { zeile: 2090, literale: ["20-45 €","300-700 €","900 €"], kommentar: false, dynamisch: false },
      { zeile: 2112, literale: ["100-300 €"], kommentar: false, dynamisch: false },
      { zeile: 2113, literale: ["300-900 €"], kommentar: false, dynamisch: false },
      { zeile: 2114, literale: ["800-2.500 €"], kommentar: false, dynamisch: false },
      { zeile: 2115, literale: ["800-2.000 €"], kommentar: false, dynamisch: false },
      { zeile: 2116, literale: ["200-500 €"], kommentar: false, dynamisch: false },
      { zeile: 2117, literale: ["150-350 €"], kommentar: false, dynamisch: false },
      { zeile: 2118, literale: ["400-1.000 €"], kommentar: false, dynamisch: false },
      { zeile: 2119, literale: ["200-500 €"], kommentar: false, dynamisch: false },
      { zeile: 2120, literale: ["3.000-8.000 €"], kommentar: false, dynamisch: false },
      { zeile: 2122, literale: ["1.500-3.500 €","3.000 €","10.000 €"], kommentar: false, dynamisch: false },
      { zeile: 2130, literale: ["65-110 €"], kommentar: false, dynamisch: false },
      { zeile: 2131, literale: ["90-160 €"], kommentar: false, dynamisch: false },
      { zeile: 2132, literale: ["50-85 €"], kommentar: false, dynamisch: false },
      { zeile: 2133, literale: ["100-180 €"], kommentar: false, dynamisch: false },
      { zeile: 2134, literale: ["20-45 €"], kommentar: false, dynamisch: false },
      { zeile: 2135, literale: ["35-55 €"], kommentar: false, dynamisch: false },
      { zeile: 2137, literale: ["45-60 €","12 €","35 €","85-95 €"], kommentar: false, dynamisch: false },
      { zeile: 2146, literale: ["15-30 €"], kommentar: false, dynamisch: false },
      { zeile: 2147, literale: ["150 €"], kommentar: false, dynamisch: false },
      { zeile: 2148, literale: ["250 €","400-800 €"], kommentar: false, dynamisch: false },
      { zeile: 2149, literale: ["40-100 €"], kommentar: false, dynamisch: false },
      { zeile: 2150, literale: ["10-25 €"], kommentar: false, dynamisch: false },
      { zeile: 2164, literale: ["75 €"], kommentar: false, dynamisch: false },
      { zeile: 2168, literale: ["5.100 €"], kommentar: false, dynamisch: false },
      { zeile: 2169, literale: ["300 €"], kommentar: false, dynamisch: false },
      { zeile: 2170, literale: ["550 €"], kommentar: false, dynamisch: false },
      { zeile: 2171, literale: ["750 €"], kommentar: false, dynamisch: false },
      { zeile: 2172, literale: ["60 €"], kommentar: false, dynamisch: false },
      { zeile: 2173, literale: ["240 €"], kommentar: false, dynamisch: false },
      { zeile: 2174, literale: ["3.800 €"], kommentar: false, dynamisch: false },
      { zeile: 2175, literale: ["600 €"], kommentar: false, dynamisch: false },
      { zeile: 2176, literale: ["750 €"], kommentar: false, dynamisch: false },
      { zeile: 2177, literale: ["2.450 €"], kommentar: false, dynamisch: false },
      { zeile: 2179, literale: ["1.000-2.000 €","4.000-6.000 €","25.000 €"], kommentar: false, dynamisch: false },
      { zeile: 2183, literale: ["3.000-8.000 €"], kommentar: false, dynamisch: false },
      { zeile: 2204, literale: ["5 €","20.000 €"], kommentar: false, dynamisch: false },
      { zeile: 2259, literale: ["2.200-2.800 €","2.500-4.500 €"], kommentar: false, dynamisch: false },
      { zeile: 2265, literale: ["2.200 bis 2.800 €","3.200 €","1.550 bis 1.950 €","150 bis 400 €"], kommentar: false, dynamisch: false },
      { zeile: 2266, literale: ["2.500 bis 4.500 €","25 bis 45 €"], kommentar: false, dynamisch: false },
      { zeile: 2267, literale: ["30-45 €","30 €"], kommentar: false, dynamisch: false },
      { zeile: 2269, literale: ["1-3 €","200 bis 500 €"], kommentar: false, dynamisch: false },
      { zeile: 2274, literale: ["2.200 bis 2.800 €","1.550-1.950 €","2.500 bis 4.500 €","8.000-12.000 €"], kommentar: false, dynamisch: false },
      { zeile: 2278, literale: ["2.000-2.300 €"], kommentar: false, dynamisch: false },
      { zeile: 2279, literale: ["2.300-2.800 €"], kommentar: false, dynamisch: false },
      { zeile: 2280, literale: ["2.800-3.400 €"], kommentar: false, dynamisch: false },
      { zeile: 2281, literale: ["150-400 €"], kommentar: false, dynamisch: false },
      { zeile: 2290, literale: ["28 €","34 €","42 €"], kommentar: false, dynamisch: false },
      { zeile: 2291, literale: ["3.530 €","6.430 €","10.580 €"], kommentar: false, dynamisch: false },
      { zeile: 2292, literale: ["650 €","800 €","1.100 €"], kommentar: false, dynamisch: false },
      { zeile: 2293, literale: ["180 €","280 €","400 €"], kommentar: false, dynamisch: false },
      { zeile: 2294, literale: ["70 €","70 €","80 €"], kommentar: false, dynamisch: false },
      { zeile: 2295, literale: ["150 €","250 €","400 €"], kommentar: false, dynamisch: false },
      { zeile: 2296, literale: ["2.480 €","5.030 €","8.600 €"], kommentar: false, dynamisch: false },
      { zeile: 2298, literale: ["250-450 €"], kommentar: false, dynamisch: false },
      { zeile: 2306, literale: ["20-35 €","55-90 €"], kommentar: false, dynamisch: false },
      { zeile: 2315, literale: ["2.500 €","1.500 €"], kommentar: false, dynamisch: false },
      { zeile: 2396, literale: ["80-180 €","45-90 €"], kommentar: false, dynamisch: false },
      { zeile: 2397, literale: ["2.200-3.800 €"], kommentar: false, dynamisch: false },
      { zeile: 2398, literale: ["500-2.000 €"], kommentar: false, dynamisch: false },
      { zeile: 2399, literale: ["8-15 €","5-10 €","20-40 €"], kommentar: false, dynamisch: false },
      { zeile: 2411, literale: ["80-120 €"], kommentar: false, dynamisch: false },
      { zeile: 2412, literale: ["100-140 €"], kommentar: false, dynamisch: false },
      { zeile: 2413, literale: ["120-180 €"], kommentar: false, dynamisch: false },
      { zeile: 2414, literale: ["45-90 €"], kommentar: false, dynamisch: false },
      { zeile: 2415, literale: ["45-75 €"], kommentar: false, dynamisch: false },
      { zeile: 2416, literale: ["40-70 €"], kommentar: false, dynamisch: false },
      { zeile: 2418, literale: ["40-70 €"], kommentar: false, dynamisch: false },
      { zeile: 2422, literale: ["68 €"], kommentar: false, dynamisch: false },
      { zeile: 2426, literale: ["4.760 €"], kommentar: false, dynamisch: false },
      { zeile: 2427, literale: ["600 €"], kommentar: false, dynamisch: false },
      { zeile: 2428, literale: ["520 €"], kommentar: false, dynamisch: false },
      { zeile: 2429, literale: ["65 €"], kommentar: false, dynamisch: false },
      { zeile: 2430, literale: ["250 €"], kommentar: false, dynamisch: false },
      { zeile: 2431, literale: ["3.325 €"], kommentar: false, dynamisch: false },
      { zeile: 2437, literale: ["500-1.200 €"], kommentar: false, dynamisch: false },
      { zeile: 2438, literale: ["20-60 €"], kommentar: false, dynamisch: false },
      { zeile: 2439, literale: ["10-25 €"], kommentar: false, dynamisch: false },
      { zeile: 2440, literale: ["25-65 €"], kommentar: false, dynamisch: false },
      { zeile: 2447, literale: ["55 €"], kommentar: false, dynamisch: false },
      { zeile: 2451, literale: ["3.000 €"], kommentar: false, dynamisch: false },
    ],
  },
  {
    datei: "src/lib/seo-data/magazin-2.ts",
    bereich: "redaktionell",
    treffer: [
      { zeile: 42, literale: ["400-1.500 €","3.000 €","2.000-6.000 €","8.000-15.000 €"], kommentar: false, dynamisch: false },
      { zeile: 52, literale: ["1.000 €","50 €"], kommentar: false, dynamisch: false },
      { zeile: 56, literale: ["400-1.500 €"], kommentar: false, dynamisch: false },
      { zeile: 60, literale: ["400-1.500 €"], kommentar: false, dynamisch: false },
      { zeile: 61, literale: ["300-900 €"], kommentar: false, dynamisch: false },
      { zeile: 62, literale: ["2.000-6.000 €"], kommentar: false, dynamisch: false },
      { zeile: 63, literale: ["3.000-10.000 €"], kommentar: false, dynamisch: false },
      { zeile: 64, literale: ["1.200-3.500 €"], kommentar: false, dynamisch: false },
      { zeile: 65, literale: ["250-500 €"], kommentar: false, dynamisch: false },
      { zeile: 66, literale: ["60-150 €"], kommentar: false, dynamisch: false },
      { zeile: 67, literale: ["500-1.500 €","30-80 €"], kommentar: false, dynamisch: false },
      { zeile: 69, literale: ["15.000-40.000 €","1.800-4.000 €"], kommentar: false, dynamisch: false },
      { zeile: 75, literale: ["15.000-40.000 €","2.000 €"], kommentar: false, dynamisch: false },
      { zeile: 79, literale: ["40-70 €","2.000-4.000 €"], kommentar: false, dynamisch: false },
      { zeile: 115, literale: ["1.500 €","25.000 €"], kommentar: false, dynamisch: false },
      { zeile: 116, literale: ["33.500 €","50 €","90.000 €","2.500 €"], kommentar: false, dynamisch: false },
      { zeile: 117, literale: ["0 €","20.000-50.000 €"], kommentar: false, dynamisch: false },
      { zeile: 118, literale: ["35.000 €","115.000 €"], kommentar: false, dynamisch: false },
      { zeile: 134, literale: ["38 €"], kommentar: false, dynamisch: false },
      { zeile: 144, literale: ["55 €","2.100 €","480 €","4.300 €","1.340 €"], kommentar: false, dynamisch: false },
      { zeile: 146, literale: ["25.000 €"], kommentar: false, dynamisch: false },
      { zeile: 162, literale: ["30-70 €","50-70 €","30-45 €","450 €"], kommentar: false, dynamisch: false },
      { zeile: 163, literale: ["20-60 €"], kommentar: false, dynamisch: false },
      { zeile: 165, literale: ["15-35 €"], kommentar: false, dynamisch: false },
      { zeile: 198, literale: ["50-70 €","750-1.100 €"], kommentar: false, dynamisch: false },
      { zeile: 199, literale: ["40-60 €","600-900 €"], kommentar: false, dynamisch: false },
      { zeile: 200, literale: ["30-45 €","450-650 €"], kommentar: false, dynamisch: false },
      { zeile: 204, literale: ["10 €"], kommentar: false, dynamisch: false },
      { zeile: 219, literale: ["45 €"], kommentar: false, dynamisch: false },
      { zeile: 223, literale: ["65 €","4.160 €"], kommentar: false, dynamisch: false },
      { zeile: 224, literale: ["720 €"], kommentar: false, dynamisch: false },
      { zeile: 225, literale: ["500 €"], kommentar: false, dynamisch: false },
      { zeile: 226, literale: ["150 €"], kommentar: false, dynamisch: false },
      { zeile: 227, literale: ["200 €"], kommentar: false, dynamisch: false },
      { zeile: 228, literale: ["2.590 €"], kommentar: false, dynamisch: false },
      { zeile: 230, literale: ["3.500-4.500 €"], kommentar: false, dynamisch: false },
      { zeile: 234, literale: ["20-60 €"], kommentar: false, dynamisch: false },
      { zeile: 245, literale: ["90-160 €"], kommentar: false, dynamisch: false },
      { zeile: 247, literale: ["250-500 €"], kommentar: false, dynamisch: false },
      { zeile: 250, literale: ["500-2.000 €"], kommentar: false, dynamisch: false },
      { zeile: 258, literale: ["100 €"], kommentar: false, dynamisch: false },
      { zeile: 266, literale: ["3-5 €"], kommentar: false, dynamisch: false },
      { zeile: 272, literale: ["2.500 €"], kommentar: false, dynamisch: false },
      { zeile: 284, literale: ["55 €","35-55 €","25 €"], kommentar: false, dynamisch: false },
      { zeile: 285, literale: ["800-2.500 €"], kommentar: false, dynamisch: false },
      { zeile: 287, literale: ["40 €","45-55 €","2.500-3.500 €"], kommentar: false, dynamisch: false },
      { zeile: 292, literale: ["10.000-20.000 €","25-55 €"], kommentar: false, dynamisch: false },
      { zeile: 313, literale: ["1.500 €"], kommentar: false, dynamisch: false },
      { zeile: 317, literale: ["12-25 €"], kommentar: false, dynamisch: false },
      { zeile: 323, literale: ["40-55 €","170-230 €"], kommentar: false, dynamisch: false },
      { zeile: 324, literale: ["32-45 €","140-190 €"], kommentar: false, dynamisch: false },
      { zeile: 325, literale: ["25-38 €","110-160 €"], kommentar: false, dynamisch: false },
      { zeile: 341, literale: ["40 €"], kommentar: false, dynamisch: false },
      { zeile: 345, literale: ["55 €","45 €","245 €"], kommentar: false, dynamisch: false },
      { zeile: 346, literale: ["40 €"], kommentar: false, dynamisch: false },
      { zeile: 347, literale: ["20 €"], kommentar: false, dynamisch: false },
      { zeile: 348, literale: ["185 €"], kommentar: false, dynamisch: false },
      { zeile: 350, literale: ["2.960 €"], kommentar: false, dynamisch: false },
      { zeile: 354, literale: ["45 €"], kommentar: false, dynamisch: false },
      { zeile: 365, literale: ["50-75 €"], kommentar: false, dynamisch: false },
      { zeile: 366, literale: ["42-58 €"], kommentar: false, dynamisch: false },
      { zeile: 367, literale: ["35-50 €"], kommentar: false, dynamisch: false },
      { zeile: 368, literale: ["5-25 €"], kommentar: false, dynamisch: false },
      { zeile: 370, literale: ["3-5 €"], kommentar: false, dynamisch: false },
      { zeile: 374, literale: ["2.000 €"], kommentar: false, dynamisch: false },
      { zeile: 397, literale: ["3.000 €"], kommentar: false, dynamisch: false },
      { zeile: 409, literale: ["40-80 €","60-80 €","35-50 €"], kommentar: false, dynamisch: false },
      { zeile: 411, literale: ["50 €","35-45 €","175-270 €"], kommentar: false, dynamisch: false },
      { zeile: 419, literale: ["40-80 €"], kommentar: false, dynamisch: false },
      { zeile: 427, literale: ["300-800 €"], kommentar: false, dynamisch: false },
      { zeile: 449, literale: ["60-80 €"], kommentar: false, dynamisch: false },
      { zeile: 450, literale: ["45-60 €"], kommentar: false, dynamisch: false },
      { zeile: 451, literale: ["35-50 €"], kommentar: false, dynamisch: false },
      { zeile: 457, literale: ["50 €"], kommentar: false, dynamisch: false },
      { zeile: 461, literale: ["38 €","304 €"], kommentar: false, dynamisch: false },
      { zeile: 462, literale: ["50 €"], kommentar: false, dynamisch: false },
      { zeile: 463, literale: ["15 €"], kommentar: false, dynamisch: false },
      { zeile: 464, literale: ["239 €"], kommentar: false, dynamisch: false },
      { zeile: 466, literale: ["5.000 €","3.600 €"], kommentar: false, dynamisch: false },
      { zeile: 473, literale: ["30 €"], kommentar: false, dynamisch: false },
      { zeile: 486, literale: ["10 €"], kommentar: false, dynamisch: false },
      { zeile: 504, literale: ["400-700 €"], kommentar: false, dynamisch: false },
      { zeile: 505, literale: ["150-400 €"], kommentar: false, dynamisch: false },
      { zeile: 506, literale: ["100-180 €"], kommentar: false, dynamisch: false },
      { zeile: 507, literale: ["120-200 €"], kommentar: false, dynamisch: false },
      { zeile: 508, literale: ["770-1.480 €"], kommentar: false, dynamisch: false },
      { zeile: 510, literale: ["300-500 €"], kommentar: false, dynamisch: false },
      { zeile: 514, literale: ["2.500 €"], kommentar: false, dynamisch: false },
      { zeile: 526, literale: ["65 €","40-65 €","25 €"], kommentar: false, dynamisch: false },
      { zeile: 536, literale: ["15.000 €","25-65 €"], kommentar: false, dynamisch: false },
      { zeile: 557, literale: ["10-25 €"], kommentar: false, dynamisch: false },
      { zeile: 563, literale: ["45-65 €","650-950 €"], kommentar: false, dynamisch: false },
      { zeile: 564, literale: ["35-50 €","500-750 €"], kommentar: false, dynamisch: false },
      { zeile: 565, literale: ["25-40 €","380-580 €"], kommentar: false, dynamisch: false },
      { zeile: 567, literale: ["120-180 €","45-70 €"], kommentar: false, dynamisch: false },
      { zeile: 581, literale: ["40 €"], kommentar: false, dynamisch: false },
      { zeile: 585, literale: ["140 €","55 €","305 €"], kommentar: false, dynamisch: false },
      { zeile: 586, literale: ["40 €"], kommentar: false, dynamisch: false },
      { zeile: 587, literale: ["30 €"], kommentar: false, dynamisch: false },
      { zeile: 588, literale: ["235 €"], kommentar: false, dynamisch: false },
      { zeile: 590, literale: ["3.760 €"], kommentar: false, dynamisch: false },
      { zeile: 606, literale: ["45-65 €"], kommentar: false, dynamisch: false },
      { zeile: 607, literale: ["25-40 €"], kommentar: false, dynamisch: false },
      { zeile: 608, literale: ["40-60 €"], kommentar: false, dynamisch: false },
      { zeile: 610, literale: ["300-600 €"], kommentar: false, dynamisch: false },
      { zeile: 628, literale: ["100-150 €","100 €"], kommentar: false, dynamisch: false },
      { zeile: 629, literale: ["130-190 €"], kommentar: false, dynamisch: false },
      { zeile: 630, literale: ["45-70 €"], kommentar: false, dynamisch: false },
      { zeile: 631, literale: ["45-65 €"], kommentar: false, dynamisch: false },
      { zeile: 633, literale: ["5-10 €"], kommentar: false, dynamisch: false },
      { zeile: 650, literale: ["800 €","55 €"], kommentar: false, dynamisch: false },
      { zeile: 657, literale: ["200-400 €"], kommentar: false, dynamisch: false },
      { zeile: 659, literale: ["40-70 €"], kommentar: false, dynamisch: false },
      { zeile: 661, literale: ["500-1.100 €"], kommentar: false, dynamisch: false },
      { zeile: 664, literale: ["300 €"], kommentar: false, dynamisch: false },
      { zeile: 694, literale: ["950 €","65 €","300-480 €"], kommentar: false, dynamisch: false },
      { zeile: 704, literale: ["5.000 €","2.000 €"], kommentar: false, dynamisch: false },
      { zeile: 710, literale: ["55 €","850 €","280 €"], kommentar: false, dynamisch: false },
      { zeile: 714, literale: ["440 €","374 €","850 €","896 €"], kommentar: false, dynamisch: false },
      { zeile: 715, literale: ["715 €","608 €","850 €","1.456 €"], kommentar: false, dynamisch: false },
      { zeile: 716, literale: ["990 €","842 €","850 €","2.016 €"], kommentar: false, dynamisch: false },
      { zeile: 717, literale: ["1.210 €","1.029 €","850 €","2.464 €"], kommentar: false, dynamisch: false },
      { zeile: 723, literale: ["300 €"], kommentar: false, dynamisch: false },
      { zeile: 735, literale: ["400-500 €"], kommentar: false, dynamisch: false },
      { zeile: 779, literale: ["25.000 €"], kommentar: false, dynamisch: false },
      { zeile: 780, literale: ["50 €","150-250 €","1.200-2.000 €"], kommentar: false, dynamisch: false },
      { zeile: 801, literale: ["20-60 €"], kommentar: false, dynamisch: false },
      { zeile: 802, literale: ["25.000 €"], kommentar: false, dynamisch: false },
      { zeile: 803, literale: ["12-30 €"], kommentar: false, dynamisch: false },
      { zeile: 817, literale: ["45 €"], kommentar: false, dynamisch: false },
      { zeile: 821, literale: ["55 €","2.310 €"], kommentar: false, dynamisch: false },
      { zeile: 822, literale: ["380 €"], kommentar: false, dynamisch: false },
      { zeile: 823, literale: ["280 €"], kommentar: false, dynamisch: false },
      { zeile: 824, literale: ["60 €"], kommentar: false, dynamisch: false },
      { zeile: 825, literale: ["1.590 €"], kommentar: false, dynamisch: false },
      { zeile: 827, literale: ["1.100 €"], kommentar: false, dynamisch: false },
      { zeile: 855, literale: ["480 €"], kommentar: false, dynamisch: false },
      { zeile: 860, literale: ["1.400-1.700 €"], kommentar: false, dynamisch: false },
      { zeile: 868, literale: ["2.800 €"], kommentar: false, dynamisch: false },
      { zeile: 885, literale: ["1.000-2.000 €"], kommentar: false, dynamisch: false },
      { zeile: 899, literale: ["800-1.500 €"], kommentar: false, dynamisch: false },
    ],
  },
  {
    datei: "src/lib/seo-data/cities.ts",
    bereich: "redaktionell",
    treffer: [
      { zeile: 15, literale: ["45-75 €"], kommentar: true, dynamisch: false },
      { zeile: 16, literale: ["25 €"], kommentar: true, dynamisch: false },
      { zeile: 68, literale: ["45-75 €","60-100 €","120-250 €"], kommentar: false, dynamisch: false },
      { zeile: 72, literale: ["45 €","75 €"], kommentar: false, dynamisch: false },
      { zeile: 80, literale: ["30–60 €"], kommentar: false, dynamisch: false },
      { zeile: 84, literale: ["120 €","250 €"], kommentar: false, dynamisch: false },
      { zeile: 104, literale: ["25-50 €","40-70 €","90-180 €"], kommentar: false, dynamisch: false },
      { zeile: 108, literale: ["25 €","40–55 €"], kommentar: false, dynamisch: false },
      { zeile: 116, literale: ["26 €"], kommentar: false, dynamisch: false },
      { zeile: 124, literale: ["80–150 €","250 €"], kommentar: false, dynamisch: false },
      { zeile: 137, literale: ["200–400 €"], kommentar: false, dynamisch: false },
      { zeile: 140, literale: ["55-90 €","70-130 €","150-350 €"], kommentar: false, dynamisch: false },
      { zeile: 144, literale: ["200–400 €","55–90 €","100–250 €"], kommentar: false, dynamisch: false },
      { zeile: 156, literale: ["120–180 €","70 €"], kommentar: false, dynamisch: false },
      { zeile: 160, literale: ["200–400 €"], kommentar: false, dynamisch: false },
      { zeile: 173, literale: ["40–65 €"], kommentar: false, dynamisch: false },
      { zeile: 176, literale: ["40-65 €","55-85 €","110-220 €"], kommentar: false, dynamisch: false },
      { zeile: 192, literale: ["20 €"], kommentar: false, dynamisch: false },
      { zeile: 209, literale: ["35–60 €"], kommentar: false, dynamisch: false },
      { zeile: 212, literale: ["35-60 €","50-80 €","100-200 €"], kommentar: false, dynamisch: false },
      { zeile: 216, literale: ["65 €"], kommentar: false, dynamisch: false },
      { zeile: 220, literale: ["45–60 €","150–250 €"], kommentar: false, dynamisch: false },
      { zeile: 232, literale: ["120–200 €"], kommentar: false, dynamisch: false },
      { zeile: 248, literale: ["40-70 €","55-90 €","110-220 €"], kommentar: false, dynamisch: false },
      { zeile: 252, literale: ["40 €","70 €","55–90 €","110–220 €"], kommentar: false, dynamisch: false },
      { zeile: 260, literale: ["26 €"], kommentar: false, dynamisch: false },
      { zeile: 284, literale: ["45-70 €","55-90 €","100-200 €"], kommentar: false, dynamisch: false },
      { zeile: 288, literale: ["45 €","70 €","55–90 €","100–200 €"], kommentar: false, dynamisch: false },
      { zeile: 296, literale: ["40–60 €"], kommentar: false, dynamisch: false },
      { zeile: 320, literale: ["30-55 €","40-70 €","80-150 €"], kommentar: false, dynamisch: false },
      { zeile: 324, literale: ["30 €","55 €","40–70 €","80–150 €"], kommentar: false, dynamisch: false },
      { zeile: 332, literale: ["30–40 €"], kommentar: false, dynamisch: false },
      { zeile: 356, literale: ["25-45 €","35-60 €","70-140 €"], kommentar: false, dynamisch: false },
      { zeile: 360, literale: ["25–45 €","35–60 €","70–140 €"], kommentar: false, dynamisch: false },
      { zeile: 368, literale: ["25–30 €"], kommentar: false, dynamisch: false },
      { zeile: 392, literale: ["30-50 €","40-62 €","75-140 €"], kommentar: false, dynamisch: false },
      { zeile: 396, literale: ["30 €","50 €","40–62 €","75–140 €"], kommentar: false, dynamisch: false },
      { zeile: 404, literale: ["30 €"], kommentar: false, dynamisch: false },
      { zeile: 429, literale: ["20-40 €","30-55 €","70-140 €"], kommentar: false, dynamisch: false },
      { zeile: 431, literale: ["20 €","40 €"], kommentar: false, dynamisch: false },
      { zeile: 433, literale: ["20–40 €"], kommentar: false, dynamisch: false },
      { zeile: 435, literale: ["30 €"], kommentar: false, dynamisch: false },
      { zeile: 447, literale: ["20 €"], kommentar: false, dynamisch: false },
      { zeile: 450, literale: ["20-45 €","30-60 €","80-150 €"], kommentar: false, dynamisch: false },
      { zeile: 452, literale: ["45 €"], kommentar: false, dynamisch: false },
      { zeile: 453, literale: ["40–60 €","30 €"], kommentar: false, dynamisch: false },
      { zeile: 456, literale: ["26 €"], kommentar: false, dynamisch: false },
      { zeile: 468, literale: ["25–45 €"], kommentar: false, dynamisch: false },
      { zeile: 471, literale: ["25-45 €","35-55 €","75-140 €"], kommentar: false, dynamisch: false },
      { zeile: 474, literale: ["30–45 €","25 €"], kommentar: false, dynamisch: false },
      { zeile: 477, literale: ["20–40 €"], kommentar: false, dynamisch: false },
      { zeile: 489, literale: ["35–55 €"], kommentar: false, dynamisch: false },
      { zeile: 492, literale: ["35-55 €","45-70 €","90-170 €"], kommentar: false, dynamisch: false },
      { zeile: 494, literale: ["35–55 €","55–90 €"], kommentar: false, dynamisch: false },
      { zeile: 497, literale: ["45–70 €","40 €"], kommentar: false, dynamisch: false },
      { zeile: 510, literale: ["20 €"], kommentar: false, dynamisch: false },
      { zeile: 513, literale: ["20-35 €","25-45 €","60-120 €"], kommentar: false, dynamisch: false },
      { zeile: 515, literale: ["20 €","35 €"], kommentar: false, dynamisch: false },
      { zeile: 518, literale: ["30–35 €"], kommentar: false, dynamisch: false },
      { zeile: 519, literale: ["26 €"], kommentar: false, dynamisch: false },
      { zeile: 531, literale: ["20–40 €"], kommentar: false, dynamisch: false },
      { zeile: 534, literale: ["20-40 €","28-50 €","65-130 €"], kommentar: false, dynamisch: false },
      { zeile: 536, literale: ["20–40 €","30–40 €","20 €"], kommentar: false, dynamisch: false },
      { zeile: 537, literale: ["20–28 €"], kommentar: false, dynamisch: false },
      { zeile: 552, literale: ["20–38 €"], kommentar: false, dynamisch: false },
      { zeile: 555, literale: ["20-38 €","28-48 €","60-120 €"], kommentar: false, dynamisch: false },
      { zeile: 558, literale: ["30–38 €","20 €"], kommentar: false, dynamisch: false },
      { zeile: 561, literale: ["40–70 €"], kommentar: false, dynamisch: false },
      { zeile: 573, literale: ["25–45 €"], kommentar: false, dynamisch: false },
      { zeile: 576, literale: ["25-45 €","32-55 €","70-140 €"], kommentar: false, dynamisch: false },
      { zeile: 579, literale: ["32–45 €","25 €"], kommentar: false, dynamisch: false },
      { zeile: 581, literale: ["32 €"], kommentar: false, dynamisch: false },
      { zeile: 594, literale: ["35–60 €"], kommentar: false, dynamisch: false },
      { zeile: 597, literale: ["35-60 €","45-75 €","100-190 €"], kommentar: false, dynamisch: false },
      { zeile: 601, literale: ["55–75 €"], kommentar: false, dynamisch: false },
      { zeile: 603, literale: ["45–75 €","180–350 €"], kommentar: false, dynamisch: false },
      { zeile: 615, literale: ["35–55 €"], kommentar: false, dynamisch: false },
      { zeile: 618, literale: ["35-55 €","40-65 €","85-160 €"], kommentar: false, dynamisch: false },
      { zeile: 621, literale: ["45–55 €","50–65 €","35 €"], kommentar: false, dynamisch: false },
    ],
  },
  {
    datei: "src/lib/seo-data/city-guides.ts",
    bereich: "redaktionell",
    treffer: [
      { zeile: 42, literale: ["60 €"], kommentar: false, dynamisch: false },
      { zeile: 50, literale: ["30–60 €","45–75 €","35–45 €","250–350 €"], kommentar: false, dynamisch: false },
      { zeile: 56, literale: ["25 €"], kommentar: false, dynamisch: false },
      { zeile: 64, literale: ["26 €","25–40 €","80–150 €","200 €"], kommentar: false, dynamisch: false },
      { zeile: 70, literale: ["55 €","60–90 €","120–180 €","45–60 €"], kommentar: false, dynamisch: false },
      { zeile: 78, literale: ["50 €","70 €","150–250 €"], kommentar: false, dynamisch: false },
      { zeile: 92, literale: ["20 €","40–65 €","50–75 €","60–90 €"], kommentar: false, dynamisch: false },
      { zeile: 98, literale: ["35–60 €"], kommentar: false, dynamisch: false },
      { zeile: 106, literale: ["26 €","35–60 €","120–220 €"], kommentar: false, dynamisch: false },
      { zeile: 112, literale: ["70–100 €","90–140 €","40–70 €"], kommentar: false, dynamisch: false },
      { zeile: 120, literale: ["26 €","70 €","130 €","400 €"], kommentar: false, dynamisch: false },
      { zeile: 126, literale: ["45–70 €"], kommentar: false, dynamisch: false },
      { zeile: 134, literale: ["40–60 €","45–70 €","45–70 €","90–130 €","150–280 €"], kommentar: false, dynamisch: false },
      { zeile: 140, literale: ["30–55 €"], kommentar: false, dynamisch: false },
      { zeile: 148, literale: ["30–40 €","30–55 €","100–180 €"], kommentar: false, dynamisch: false },
      { zeile: 162, literale: ["40 €","35–55 €","30–42 €","50–70 €","100–140 €","130–230 €"], kommentar: false, dynamisch: false },
      { zeile: 168, literale: ["25 €"], kommentar: false, dynamisch: false },
      { zeile: 176, literale: ["25–30 €","25–45 €","25–35 €","45–65 €","80–120 €"], kommentar: false, dynamisch: false },
      { zeile: 182, literale: ["25–45 €"], kommentar: false, dynamisch: false },
      { zeile: 190, literale: ["20–40 €","25–45 €","28–38 €","45–65 €","90–130 €","100–200 €"], kommentar: false, dynamisch: false },
      { zeile: 196, literale: ["20 €"], kommentar: false, dynamisch: false },
      { zeile: 204, literale: ["26 €","20–40 €","22–32 €","40–60 €","80–110 €","100–180 €"], kommentar: false, dynamisch: false },
      { zeile: 210, literale: ["20 €"], kommentar: false, dynamisch: false },
      { zeile: 214, literale: ["35–45 €"], kommentar: false, dynamisch: false },
      { zeile: 218, literale: ["26 €","20–45 €","45–65 €","55–80 €","100–200 €"], kommentar: false, dynamisch: false },
      { zeile: 224, literale: ["30 €"], kommentar: false, dynamisch: false },
      { zeile: 232, literale: ["30 €","30–50 €","25–35 €","42–60 €","85–115 €","90–160 €"], kommentar: false, dynamisch: false },
    ],
  },
  {
    datei: "src/lib/seo-data/verticals.ts",
    bereich: "redaktionell",
    treffer: [
      { zeile: 11, literale: ["45 €"], kommentar: true, dynamisch: false },
      { zeile: 71, literale: ["40–60 €","60–90 €","30–50 €"], kommentar: false, dynamisch: false },
      { zeile: 83, literale: ["10-30 €"], kommentar: false, dynamisch: false },
      { zeile: 118, literale: ["45 €"], kommentar: false, dynamisch: false },
      { zeile: 123, literale: ["40–70 €","90 €","25 €"], kommentar: false, dynamisch: false },
      { zeile: 149, literale: ["90 €","60–120 €"], kommentar: false, dynamisch: false },
      { zeile: 171, literale: ["50–90 €","70–130 €","45–70 €","15–25 €"], kommentar: false, dynamisch: false },
      { zeile: 179, literale: ["120–200 €","140–180 €","90–140 €","250–500 €","50-90 €"], kommentar: false, dynamisch: false },
      { zeile: 187, literale: ["15-40 €"], kommentar: false, dynamisch: false },
      { zeile: 197, literale: ["45-90 €","35-60 €"], kommentar: false, dynamisch: false },
      { zeile: 200, literale: ["35 €"], kommentar: false, dynamisch: false },
      { zeile: 219, literale: ["35-60 €","30 €","50-65 €"], kommentar: false, dynamisch: false },
      { zeile: 223, literale: ["60 €","300-400 €"], kommentar: false, dynamisch: false },
      { zeile: 231, literale: ["5-10 €"], kommentar: false, dynamisch: false },
      { zeile: 235, literale: ["60-100 €"], kommentar: false, dynamisch: false },
      { zeile: 245, literale: ["90-180 €","75 €"], kommentar: false, dynamisch: false },
      { zeile: 266, literale: ["45-75 €","90 €","18-30 €"], kommentar: false, dynamisch: false },
      { zeile: 274, literale: ["130 €","390 €","60 €","330 €"], kommentar: false, dynamisch: false },
      { zeile: 278, literale: ["350-800 €"], kommentar: false, dynamisch: false },
      { zeile: 282, literale: ["40-70 €"], kommentar: false, dynamisch: false },
    ],
  },
  {
    datei: "src/app/(public)/preisvergleich/page.tsx",
    bereich: "oeffentlich",
    treffer: [
      { zeile: 24, literale: ["25 €"], kommentar: true, dynamisch: false },
      { zeile: 47, literale: ["25 €"], kommentar: false, dynamisch: false },
      { zeile: 80, literale: ["45–75 €"], kommentar: false, dynamisch: false },
      { zeile: 81, literale: ["58 €"], kommentar: false, dynamisch: false },
      { zeile: 195, literale: ["25 €","90 €","800–1.500 €","90–350 €"], kommentar: false, dynamisch: false },
      { zeile: 199, literale: ["150–200 €"], kommentar: false, dynamisch: false },
      { zeile: 203, literale: ["10–25 €","20–60 €"], kommentar: false, dynamisch: false },
      { zeile: 207, literale: ["30.000–80.000 €","2.500–6.000 €","0 €","800–1.500 €"], kommentar: false, dynamisch: false },
      { zeile: 358, literale: ["80.000 €"], kommentar: false, dynamisch: false },
      { zeile: 359, literale: ["2.500 bis 6.000 €"], kommentar: false, dynamisch: false },
      { zeile: 366, literale: ["8.000 €"], kommentar: false, dynamisch: false },
      { zeile: 367, literale: ["2.400 bis 3.200 €"], kommentar: false, dynamisch: false },
      { zeile: 371, literale: ["0 €","800 bis 1.500 €"], kommentar: false, dynamisch: false },
      { zeile: 372, literale: ["25 €"], kommentar: false, dynamisch: false },
      { zeile: 391, literale: ["0 €"], kommentar: false, dynamisch: false },
      { zeile: 392, literale: ["30.000–80.000 €"], kommentar: false, dynamisch: false },
      { zeile: 393, literale: ["0 €"], kommentar: false, dynamisch: false },
      { zeile: 397, literale: ["800–1.500 €"], kommentar: false, dynamisch: false },
      { zeile: 398, literale: ["2.500–6.000 €"], kommentar: false, dynamisch: false },
      { zeile: 399, literale: ["0 €"], kommentar: false, dynamisch: false },
    ],
  },
  {
    datei: "src/lib/seo-data/faq-master.ts",
    bereich: "redaktionell",
    treffer: [
      { zeile: 64, literale: ["40-90 €"], kommentar: false, dynamisch: false },
      { zeile: 71, literale: ["40-70 €","30 €","65-95 €","120 €"], kommentar: false, dynamisch: false },
      { zeile: 108, literale: ["22.000 €","50.000 €"], kommentar: false, dynamisch: false },
      { zeile: 115, literale: ["24.500 €"], kommentar: false, dynamisch: false },
      { zeile: 125, literale: ["15-30 €"], kommentar: false, dynamisch: false },
      { zeile: 132, literale: ["150-600 €"], kommentar: false, dynamisch: false },
      { zeile: 142, literale: ["1.500-2.200 €","2.500-4.000 €","4.000-7.000 €"], kommentar: false, dynamisch: false },
      { zeile: 149, literale: ["80-150 €","200-400 €","250-500 €"], kommentar: false, dynamisch: false },
      { zeile: 205, literale: ["800-1.500 €","45-85 €","19.000-36.000 €"], kommentar: false, dynamisch: false },
      { zeile: 221, literale: ["50-85 €","65-85 €","45-60 €","55-70 €"], kommentar: false, dynamisch: false },
      { zeile: 228, literale: ["75-120 €","60-85 €"], kommentar: false, dynamisch: false },
      { zeile: 235, literale: ["55-85 €","95 €","45-65 €"], kommentar: false, dynamisch: false },
    ],
  },
  {
    datei: "src/app/(public)/longevity/page.tsx",
    bereich: "oeffentlich",
    treffer: [
      { zeile: 4, literale: ["€39"], kommentar: true, dynamisch: false },
      { zeile: 42, literale: ["29 €"], kommentar: false, dynamisch: false },
      { zeile: 84, literale: ["29-49 €","290-390 €","30 €"], kommentar: false, dynamisch: false },
      { zeile: 88, literale: ["149 €","1.290 €"], kommentar: false, dynamisch: false },
      { zeile: 92, literale: ["490-690 €","390-490 €"], kommentar: false, dynamisch: false },
      { zeile: 96, literale: ["390 €"], kommentar: false, dynamisch: false },
      { zeile: 100, literale: ["39 €"], kommentar: false, dynamisch: false },
      { zeile: 104, literale: ["290 €"], kommentar: false, dynamisch: false },
      { zeile: 108, literale: ["1.490-2.990 €"], kommentar: false, dynamisch: false },
      { zeile: 159, literale: ["29 – 49 €","290 €"], kommentar: false, dynamisch: false },
      { zeile: 160, literale: ["149 €","1.290 €"], kommentar: false, dynamisch: false },
      { zeile: 161, literale: ["490 – 690 €"], kommentar: false, dynamisch: false },
      { zeile: 162, literale: ["39 €"], kommentar: false, dynamisch: false },
      { zeile: 163, literale: ["390 €"], kommentar: false, dynamisch: false },
      { zeile: 164, literale: ["290 €"], kommentar: false, dynamisch: false },
      { zeile: 165, literale: ["1.490 €"], kommentar: false, dynamisch: false },
    ],
  },
  {
    datei: "src/app/(public)/zahnimplantate/page.tsx",
    bereich: "oeffentlich",
    treffer: [
      { zeile: 5, literale: ["€890"], kommentar: true, dynamisch: false },
      { zeile: 43, literale: ["1.490 €"], kommentar: false, dynamisch: false },
      { zeile: 81, literale: ["1.490-1.990 €","2.290-2.890 €","600-1.200 €"], kommentar: false, dynamisch: false },
      { zeile: 85, literale: ["11.900-14.900 €","22.000-28.000 €","4.500-7.000 €"], kommentar: false, dynamisch: false },
      { zeile: 89, literale: ["590-690 €","4.700-6.900 €"], kommentar: false, dynamisch: false },
      { zeile: 105, literale: ["2.490-5.990 €"], kommentar: false, dynamisch: false },
      { zeile: 109, literale: ["3.000-8.000 €"], kommentar: false, dynamisch: false },
      { zeile: 160, literale: ["1.490 – 1.990 €"], kommentar: false, dynamisch: false },
      { zeile: 161, literale: ["2.290 – 2.890 €"], kommentar: false, dynamisch: false },
      { zeile: 162, literale: ["11.900 – 14.900 €"], kommentar: false, dynamisch: false },
      { zeile: 163, literale: ["14.900 – 17.900 €"], kommentar: false, dynamisch: false },
      { zeile: 164, literale: ["590 – 690 €"], kommentar: false, dynamisch: false },
      { zeile: 165, literale: ["2.490 – 5.990 €"], kommentar: false, dynamisch: false },
      { zeile: 166, literale: ["290 – 390 €"], kommentar: false, dynamisch: false },
      { zeile: 178, literale: ["0 €"], kommentar: false, dynamisch: false },
    ],
  },
  {
    datei: "src/app/(public)/iv-infusionen/page.tsx",
    bereich: "oeffentlich",
    treffer: [
      { zeile: 41, literale: ["99 €"], kommentar: false, dynamisch: false },
      { zeile: 83, literale: ["290 €","490 €","890 €"], kommentar: false, dynamisch: false },
      { zeile: 87, literale: ["149 €"], kommentar: false, dynamisch: false },
      { zeile: 91, literale: ["129-189 €"], kommentar: false, dynamisch: false },
      { zeile: 95, literale: ["139 €"], kommentar: false, dynamisch: false },
      { zeile: 103, literale: ["99 €"], kommentar: false, dynamisch: false },
      { zeile: 158, literale: ["290 €"], kommentar: false, dynamisch: false },
      { zeile: 159, literale: ["490 €"], kommentar: false, dynamisch: false },
      { zeile: 160, literale: ["890 €"], kommentar: false, dynamisch: false },
      { zeile: 161, literale: ["129 – 189 €"], kommentar: false, dynamisch: false },
      { zeile: 162, literale: ["149 €"], kommentar: false, dynamisch: false },
      { zeile: 163, literale: ["219 €"], kommentar: false, dynamisch: false },
      { zeile: 164, literale: ["99 €"], kommentar: false, dynamisch: false },
      { zeile: 165, literale: ["139 €"], kommentar: false, dynamisch: false },
      { zeile: 166, literale: ["219 €"], kommentar: false, dynamisch: false },
    ],
  },
  {
    datei: "src/app/(public)/haartransplantation/page.tsx",
    bereich: "oeffentlich",
    treffer: [
      { zeile: 6, literale: ["€2.000"], kommentar: true, dynamisch: false },
      { zeile: 53, literale: ["2.490–4.990 €"], kommentar: false, dynamisch: false },
      { zeile: 91, literale: ["2.490-4.990 €","3.290-4.590 €","4.290-5.990 €","1.500-2.500 €"], kommentar: false, dynamisch: false },
      { zeile: 217, literale: ["2.490 – 4.990 €"], kommentar: false, dynamisch: false },
      { zeile: 227, literale: ["3.290 – 4.590 €"], kommentar: false, dynamisch: false },
      { zeile: 237, literale: ["4.290 – 5.990 €"], kommentar: false, dynamisch: false },
      { zeile: 253, literale: ["1.890 – 2.890 €"], kommentar: false, dynamisch: false },
      { zeile: 254, literale: ["1.690 €"], kommentar: false, dynamisch: false },
      { zeile: 255, literale: ["4.990 €"], kommentar: false, dynamisch: false },
      { zeile: 256, literale: ["1.990 €"], kommentar: false, dynamisch: false },
      { zeile: 257, literale: ["1.990 €"], kommentar: false, dynamisch: false },
      { zeile: 258, literale: ["290 €","690 €"], kommentar: false, dynamisch: false },
    ],
  },
  {
    datei: "src/app/(public)/augenlasern/page.tsx",
    bereich: "oeffentlich",
    treffer: [
      { zeile: 41, literale: ["1.490 €"], kommentar: false, dynamisch: false },
      { zeile: 46, literale: ["1.490 €"], kommentar: false, dynamisch: false },
      { zeile: 56, literale: ["1.490 €"], kommentar: false, dynamisch: false },
      { zeile: 79, literale: ["1.490-1.890 €","2.490-2.990 €","1.890-2.290 €","2.290-2.990 €","2.890-5.490 €"], kommentar: false, dynamisch: false },
      { zeile: 103, literale: ["2.890-2.990 €"], kommentar: false, dynamisch: false },
      { zeile: 158, literale: ["1.490 – 1.890 €"], kommentar: false, dynamisch: false },
      { zeile: 159, literale: ["1.890 – 2.290 €"], kommentar: false, dynamisch: false },
      { zeile: 160, literale: ["2.290 – 2.990 €"], kommentar: false, dynamisch: false },
      { zeile: 161, literale: ["1.490 – 1.890 €"], kommentar: false, dynamisch: false },
      { zeile: 162, literale: ["2.890 – 2.990 €"], kommentar: false, dynamisch: false },
      { zeile: 163, literale: ["2.890 – 3.490 €"], kommentar: false, dynamisch: false },
    ],
  },
  {
    datei: "src/app/(public)/freelancer-rechner/page.tsx",
    bereich: "oeffentlich",
    treffer: [
      { zeile: 10, literale: ["2.200–3.800 €"], kommentar: true, dynamisch: false },
      { zeile: 11, literale: ["1.400–1.800 €"], kommentar: true, dynamisch: false },
      { zeile: 43, literale: ["25–60 €","45–80 €","2.200–3.800 €","1.400–1.800 €"], kommentar: false, dynamisch: false },
      { zeile: 47, literale: ["500–1.200 €","200–400 €","10–25 €"], kommentar: false, dynamisch: false },
      { zeile: 55, literale: ["20–60 €"], kommentar: false, dynamisch: false },
      { zeile: 59, literale: ["12.000 €","25.000 €"], kommentar: false, dynamisch: false },
      { zeile: 63, literale: ["25 €","90 €"], kommentar: false, dynamisch: false },
    ],
  },
  {
    datei: "src/components/HomeSEOLanding.tsx",
    bereich: "oeffentlich",
    treffer: [
      { zeile: 16, literale: ["25–75 €"], kommentar: true, dynamisch: false },
      { zeile: 17, literale: ["300 €","1.000 €"], kommentar: true, dynamisch: false },
      { zeile: 122, literale: ["25–75 €"], kommentar: false, dynamisch: false },
      { zeile: 138, literale: ["25 €","75 €","25 €","300 €","1.000 €"], kommentar: false, dynamisch: false },
      { zeile: 280, literale: ["25 €","75 €"], kommentar: false, dynamisch: false },
      { zeile: 341, literale: ["25 €"], kommentar: false, dynamisch: false },
    ],
  },
  {
    datei: "src/components/HomeClient.tsx",
    bereich: "oeffentlich",
    treffer: [
      { zeile: 7, literale: ["25 €"], kommentar: true, dynamisch: false },
      { zeile: 8, literale: ["800-1.500 €"], kommentar: true, dynamisch: false },
      { zeile: 11, literale: ["2.490 €"], kommentar: true, dynamisch: false },
      { zeile: 353, literale: ["25 €"], kommentar: false, dynamisch: false },
      { zeile: 367, literale: ["800-1.500 €"], kommentar: false, dynamisch: false },
      { zeile: 392, literale: ["2.490 €"], kommentar: false, dynamisch: false },
      { zeile: 399, literale: ["1.490 €"], kommentar: false, dynamisch: false },
      { zeile: 406, literale: ["1.490 €"], kommentar: false, dynamisch: false },
      { zeile: 413, literale: ["29 €"], kommentar: false, dynamisch: false },
      { zeile: 420, literale: ["79 €"], kommentar: false, dynamisch: false },
      { zeile: 427, literale: ["290 €"], kommentar: false, dynamisch: false },
    ],
  },
  {
    datei: "src/app/(public)/pitch/page.tsx",
    bereich: "oeffentlich",
    treffer: [
      { zeile: 7, literale: ["29 €","49 €"], kommentar: true, dynamisch: false },
      { zeile: 8, literale: ["99 €"], kommentar: true, dynamisch: false },
      { zeile: 12, literale: ["€15"], kommentar: true, dynamisch: false },
      { zeile: 14, literale: ["€150"], kommentar: true, dynamisch: false },
      { zeile: 59, literale: ["€15"], kommentar: false, dynamisch: false },
      { zeile: 66, literale: ["29€"], kommentar: false, dynamisch: false },
      { zeile: 67, literale: ["49€"], kommentar: false, dynamisch: false },
      { zeile: 68, literale: ["99€"], kommentar: false, dynamisch: false },
      { zeile: 104, literale: ["€150"], kommentar: false, dynamisch: false },
    ],
  },
  {
    datei: "src/app/(public)/freelancer-rechner/CalculatorClient.tsx",
    bereich: "oeffentlich",
    treffer: [
      { zeile: 7, literale: ["45 €","65-90 €"], kommentar: true, dynamisch: false },
      { zeile: 8, literale: ["420 €","280-450 €"], kommentar: true, dynamisch: false },
      { zeile: 17, literale: ["45 €"], kommentar: true, dynamisch: false },
      { zeile: 111, literale: ["45 €","65-90 €"], kommentar: false, dynamisch: false },
      { zeile: 123, literale: ["420 €","280-450 €"], kommentar: false, dynamisch: false },
    ],
  },
  {
    datei: "src/app/(public)/premium/page.tsx",
    bereich: "oeffentlich",
    treffer: [
      { zeile: 12, literale: ["2.490 €","1.490 €","290 €"], kommentar: true, dynamisch: false },
      { zeile: 85, literale: ["2.490 €"], kommentar: false, dynamisch: false },
      { zeile: 93, literale: ["1.490 €"], kommentar: false, dynamisch: false },
      { zeile: 101, literale: ["1.490 €"], kommentar: false, dynamisch: false },
      { zeile: 109, literale: ["29 €"], kommentar: false, dynamisch: false },
      { zeile: 116, literale: ["79 €"], kommentar: false, dynamisch: false },
      { zeile: 123, literale: ["290 €"], kommentar: false, dynamisch: false },
    ],
  },
  {
    datei: "src/app/(public)/anbieter/onboarding/page.tsx",
    bereich: "oeffentlich",
    treffer: [
      { zeile: 32, literale: ["45 €"], kommentar: true, dynamisch: false },
      { zeile: 33, literale: ["250 €"], kommentar: true, dynamisch: false },
      { zeile: 35, literale: ["25 €","28 €"], kommentar: true, dynamisch: false },
      { zeile: 67, literale: ["28 €","25 €"], kommentar: true, dynamisch: false },
      { zeile: 335, literale: ["€45"], kommentar: true, dynamisch: false },
    ],
  },
  {
    datei: "src/app/(public)/provisionsmodell/page.tsx",
    bereich: "oeffentlich",
    treffer: [
      { zeile: 6, literale: ["100€","90€"], kommentar: true, dynamisch: false },
      { zeile: 11, literale: ["0,25€"], kommentar: true, dynamisch: false },
      { zeile: 54, literale: ["100€","90€","10€"], kommentar: false, dynamisch: false },
      { zeile: 56, literale: ["0,25€"], kommentar: false, dynamisch: false },
    ],
  },
  {
    datei: "src/app/(public)/stuhlvermietung-guide/page.tsx",
    bereich: "oeffentlich",
    treffer: [
      { zeile: 4, literale: ["25-80 €"], kommentar: true, dynamisch: false },
      { zeile: 5, literale: ["1.100 €"], kommentar: true, dynamisch: false },
      { zeile: 114, literale: ["25-80 €","40-70 €","25-55 €","1.100 €"], kommentar: false, dynamisch: false },
      { zeile: 150, literale: ["25-80 €"], kommentar: false, dynamisch: false },
    ],
  },
  {
    datei: "src/app/(public)/register/anbieter/page.tsx",
    bereich: "oeffentlich",
    treffer: [
      { zeile: 7, literale: ["80–150 €"], kommentar: true, dynamisch: false },
      { zeile: 39, literale: ["80–150 €"], kommentar: false, dynamisch: false },
      { zeile: 48, literale: ["40–60 €"], kommentar: false, dynamisch: false },
      { zeile: 58, literale: ["45–75 €"], kommentar: false, dynamisch: false },
      { zeile: 67, literale: ["250–500 €"], kommentar: false, dynamisch: false },
      { zeile: 78, literale: ["35–55 €"], kommentar: false, dynamisch: false },
    ],
  },
  {
    datei: "src/app/(investor)/investor/page.tsx",
    bereich: "intern",
    treffer: [
      { zeile: 104, literale: ["€15"], kommentar: false, dynamisch: false },
      { zeile: 106, literale: ["€2"], kommentar: false, dynamisch: false },
      { zeile: 125, literale: ["€49"], kommentar: false, dynamisch: false },
      { zeile: 126, literale: ["€99"], kommentar: false, dynamisch: false },
      { zeile: 171, literale: ["€150"], kommentar: false, dynamisch: false },
    ],
  },
  {
    datei: "src/app/(public)/mieter/mein-bereich/suchen/page.tsx",
    bereich: "oeffentlich",
    treffer: [
      { zeile: 23, literale: ["15 €"], kommentar: true, dynamisch: false },
      { zeile: 24, literale: ["500 €"], kommentar: true, dynamisch: false },
      { zeile: 38, literale: ["38 €","38,50 €"], kommentar: true, dynamisch: false },
    ],
  },
  {
    datei: "src/app/(public)/mieter/wie-es-funktioniert/page.tsx",
    bereich: "oeffentlich",
    treffer: [
      { zeile: 4, literale: ["50€"], kommentar: true, dynamisch: false },
      { zeile: 6, literale: ["30€"], kommentar: true, dynamisch: false },
      { zeile: 55, literale: ["50€"], kommentar: false, dynamisch: false },
      { zeile: 56, literale: ["30€"], kommentar: false, dynamisch: false },
    ],
  },
  {
    datei: "src/__tests__/e2e/booking-flow.test.ts",
    bereich: "test",
    treffer: [
      { zeile: 284, literale: ["50,00 €"], kommentar: false, dynamisch: false },
      { zeile: 642, literale: ["50,00 €"], kommentar: false, dynamisch: false },
      { zeile: 677, literale: ["50,00 €"], kommentar: false, dynamisch: false },
    ],
  },
  {
    datei: "src/__tests__/e2e/dashboard-und-favoriten.test.ts",
    bereich: "test",
    treffer: [
      { zeile: 8, literale: ["480 EUR"], kommentar: true, dynamisch: false },
      { zeile: 9, literale: ["90 EUR"], kommentar: true, dynamisch: false },
      { zeile: 10, literale: ["85 EUR"], kommentar: true, dynamisch: false },
    ],
  },
  {
    datei: "src/__tests__/e2e/payment-flow.test.ts",
    bereich: "test",
    treffer: [
      { zeile: 1463, literale: ["5 €"], kommentar: true, dynamisch: false },
      { zeile: 1703, literale: ["0 €"], kommentar: false, dynamisch: false },
      { zeile: 1719, literale: ["0 €"], kommentar: false, dynamisch: false },
    ],
  },
  {
    datei: "src/__tests__/track-23-benachrichtigungswege.test.ts",
    bereich: "test",
    treffer: [
      { zeile: 485, literale: ["89,00 EUR"], kommentar: false, dynamisch: false },
      { zeile: 670, literale: ["89,00 EUR"], kommentar: false, dynamisch: false },
      { zeile: 702, literale: ["89,00 EUR"], kommentar: true, dynamisch: false },
    ],
  },
  {
    datei: "src/app/(owner)/owner/authorities/page.tsx",
    bereich: "geteilt",
    treffer: [
      { zeile: 27, literale: ["99 €","299 €","39 €"], kommentar: false, dynamisch: false },
    ],
  },
  {
    datei: "src/app/api/me/dashboard-stats/route.ts",
    bereich: "api",
    treffer: [
      { zeile: 11, literale: ["480 EUR"], kommentar: true, dynamisch: false },
      { zeile: 12, literale: ["90 EUR"], kommentar: true, dynamisch: false },
      { zeile: 13, literale: ["85 EUR"], kommentar: true, dynamisch: false },
    ],
  },
  {
    datei: "src/components/provider/DashboardClient.tsx",
    bereich: "geteilt",
    treffer: [
      { zeile: 298, literale: ["0,00 €"], kommentar: true, dynamisch: false },
      { zeile: 631, literale: ["49 €"], kommentar: false, dynamisch: false },
      { zeile: 654, literale: ["49 €"], kommentar: false, dynamisch: false },
    ],
  },
  {
    datei: "src/__tests__/anon-exposure-and-mock-residue.test.ts",
    bereich: "test",
    treffer: [
      { zeile: 159, literale: ["65 EUR"], kommentar: true, dynamisch: false },
      { zeile: 292, literale: ["€480"], kommentar: true, dynamisch: false },
    ],
  },
  {
    datei: "src/__tests__/e2e/inserat-lebenszyklus.test.ts",
    bereich: "test",
    treffer: [
      { zeile: 15, literale: ["0 €"], kommentar: true, dynamisch: false },
      { zeile: 343, literale: ["0 €"], kommentar: true, dynamisch: false },
    ],
  },
  {
    datei: "src/__tests__/keine-erfundene-bestaetigung.test.ts",
    bereich: "test",
    treffer: [
      { zeile: 26, literale: ["5 €"], kommentar: true, dynamisch: false },
      { zeile: 29, literale: ["15 €"], kommentar: true, dynamisch: false },
    ],
  },
  {
    datei: "src/app/(protected)/booking/[salonId]/page.tsx",
    bereich: "angemeldet",
    treffer: [
      { zeile: 38, literale: ["5 €"], kommentar: true, dynamisch: false },
      { zeile: 41, literale: ["15 €"], kommentar: true, dynamisch: false },
    ],
  },
  {
    datei: "src/app/(public)/inserat/[id]/page.tsx",
    bereich: "oeffentlich",
    treffer: [
      { zeile: 13, literale: ["1500 €"], kommentar: true, dynamisch: false },
      { zeile: 17, literale: ["15 €"], kommentar: true, dynamisch: false },
    ],
  },
  {
    datei: "src/app/(public)/landing/page.tsx",
    bereich: "oeffentlich",
    treffer: [
      { zeile: 4, literale: ["€15"], kommentar: true, dynamisch: false },
      { zeile: 273, literale: ["€15"], kommentar: false, dynamisch: false },
    ],
  },
  {
    datei: "src/app/(public)/rentals/page.tsx",
    bereich: "oeffentlich",
    treffer: [
      { zeile: 4, literale: ["25 €"], kommentar: true, dynamisch: false },
      { zeile: 29, literale: ["25 €"], kommentar: false, dynamisch: false },
    ],
  },
  {
    datei: "src/app/api/rental-listings/route.ts",
    bereich: "api",
    treffer: [
      { zeile: 19, literale: ["90 €"], kommentar: true, dynamisch: false },
      { zeile: 20, literale: ["500 €"], kommentar: true, dynamisch: false },
    ],
  },
  {
    datei: "src/app/api/stripe/webhook/route.ts",
    bereich: "api",
    treffer: [
      { zeile: 965, literale: ["5 €","500 €"], kommentar: true, dynamisch: false },
    ],
  },
  {
    datei: "src/app/page.tsx",
    bereich: "oeffentlich",
    treffer: [
      { zeile: 4, literale: ["25 €"], kommentar: true, dynamisch: false },
      { zeile: 31, literale: ["25 €"], kommentar: false, dynamisch: false },
    ],
  },
  {
    datei: "src/components/provider/__tests__/DashboardClient.stripe.test.tsx",
    bereich: "test",
    treffer: [
      { zeile: 211, literale: ["0,00 €"], kommentar: true, dynamisch: false },
      { zeile: 220, literale: ["0,00 €"], kommentar: true, dynamisch: false },
    ],
  },
  {
    datei: "src/lib/constants.ts",
    bereich: "geteilt",
    treffer: [
      { zeile: 42, literale: ["5 €"], kommentar: true, dynamisch: false },
      { zeile: 43, literale: ["15 €"], kommentar: true, dynamisch: false },
    ],
  },
  {
    datei: "src/lib/seo.ts",
    bereich: "geteilt",
    treffer: [
      { zeile: 377, literale: ["45-75 €"], kommentar: true, dynamisch: false },
      { zeile: 388, literale: ["45-75 €"], kommentar: true, dynamisch: false },
    ],
  },
  {
    datei: "src/__tests__/e2e/admin-provisionen.test.ts",
    bereich: "test",
    treffer: [
      { zeile: 12, literale: ["0 €"], kommentar: true, dynamisch: false },
    ],
  },
  {
    datei: "src/__tests__/e2e/provider-onboarding.test.ts",
    bereich: "test",
    treffer: [
      { zeile: 14, literale: ["45 €"], kommentar: true, dynamisch: false },
    ],
  },
  {
    datei: "src/__tests__/keine-erfundenen-zusagen.test.ts",
    bereich: "test",
    treffer: [
      { zeile: 6, literale: ["5 €"], kommentar: true, dynamisch: false },
    ],
  },
  {
    datei: "src/app/(admin)/admin/affiliate/AdminAffiliateClient.tsx",
    bereich: "intern",
    treffer: [
      { zeile: 249, literale: ["28,90 €"], kommentar: false, dynamisch: false },
    ],
  },
  {
    datei: "src/app/(admin)/admin/mis/page.tsx",
    bereich: "intern",
    treffer: [
      { zeile: 523, literale: ["0,00 €"], kommentar: true, dynamisch: false },
    ],
  },
  {
    datei: "src/app/(admin)/admin/page.tsx",
    bereich: "intern",
    treffer: [
      { zeile: 53, literale: ["0,00 €"], kommentar: true, dynamisch: false },
    ],
  },
  {
    datei: "src/app/(admin)/admin/provisionen/page.tsx",
    bereich: "intern",
    treffer: [
      { zeile: 17, literale: ["0 €"], kommentar: true, dynamisch: false },
    ],
  },
  {
    datei: "src/app/(protected)/account/page.tsx",
    bereich: "angemeldet",
    treffer: [
      { zeile: 267, literale: ["0,00 €"], kommentar: false, dynamisch: false },
    ],
  },
  {
    datei: "src/app/(public)/anbieter/mein-salon/page.tsx",
    bereich: "oeffentlich",
    treffer: [
      { zeile: 42, literale: ["€480"], kommentar: true, dynamisch: false },
    ],
  },
  {
    datei: "src/app/(public)/karte/page.tsx",
    bereich: "oeffentlich",
    treffer: [
      { zeile: 42, literale: ["65 EUR"], kommentar: true, dynamisch: false },
    ],
  },
  {
    datei: "src/app/(public)/mieter/mein-bereich/angebote/page.tsx",
    bereich: "oeffentlich",
    treffer: [
      { zeile: 14, literale: ["€60"], kommentar: true, dynamisch: false },
    ],
  },
  {
    datei: "src/app/(public)/mieter/mein-bereich/favoriten/page.tsx",
    bereich: "oeffentlich",
    treffer: [
      { zeile: 14, literale: ["€110"], kommentar: true, dynamisch: false },
    ],
  },
  {
    datei: "src/app/(public)/mieter/mein-bereich/page.tsx",
    bereich: "oeffentlich",
    treffer: [
      { zeile: 24, literale: ["€85"], kommentar: true, dynamisch: false },
    ],
  },
  {
    datei: "src/app/(public)/mieter/mein-bereich/verlauf/page.tsx",
    bereich: "oeffentlich",
    treffer: [
      { zeile: 14, literale: ["€85"], kommentar: true, dynamisch: false },
    ],
  },
  {
    datei: "src/app/(public)/vermieter/mein-inserat/page.tsx",
    bereich: "oeffentlich",
    treffer: [
      { zeile: 25, literale: ["€90"], kommentar: true, dynamisch: false },
    ],
  },
  {
    datei: "src/app/(public)/vermieter/mein-inserat/umsatz/page.tsx",
    bereich: "oeffentlich",
    treffer: [
      { zeile: 449, literale: ["0 €"], kommentar: true, dynamisch: false },
    ],
  },
  {
    datei: "src/app/api/admin/commissions/route.ts",
    bereich: "api",
    treffer: [
      { zeile: 16, literale: ["0 €"], kommentar: true, dynamisch: false },
    ],
  },
  {
    datei: "src/app/api/admin/mis/route.ts",
    bereich: "api",
    treffer: [
      { zeile: 392, literale: ["0,00 €"], kommentar: true, dynamisch: false },
    ],
  },
  {
    datei: "src/app/api/cron/hard-delete/route.ts",
    bereich: "api",
    treffer: [
      { zeile: 64, literale: ["89,00 EUR"], kommentar: true, dynamisch: false },
    ],
  },
  {
    datei: "src/app/api/me/listing/route.ts",
    bereich: "api",
    treffer: [
      { zeile: 104, literale: ["0 €"], kommentar: true, dynamisch: false },
    ],
  },
  {
    datei: "src/app/api/onboarding/salon/route.ts",
    bereich: "api",
    treffer: [
      { zeile: 30, literale: ["100.000 €"], kommentar: true, dynamisch: false },
    ],
  },
  {
    datei: "src/app/api/provider/services/route.ts",
    bereich: "api",
    treffer: [
      { zeile: 34, literale: ["100.000 €"], kommentar: true, dynamisch: false },
    ],
  },
  {
    datei: "src/app/api/register-provider/route.ts",
    bereich: "api",
    treffer: [
      { zeile: 32, literale: ["45 €"], kommentar: true, dynamisch: false },
    ],
  },
  {
    datei: "src/app/api/rental-equipment/__tests__/crud.e2e.test.ts",
    bereich: "test",
    treffer: [
      { zeile: 412, literale: ["0 €"], kommentar: true, dynamisch: false },
    ],
  },
  {
    datei: "src/app/api/rental-requests/route.ts",
    bereich: "api",
    treffer: [
      { zeile: 98, literale: ["0 €"], kommentar: true, dynamisch: false },
    ],
  },
  {
    datei: "src/components/cart/CartDrawer.tsx",
    bereich: "geteilt",
    treffer: [
      { zeile: 240, literale: ["50 €"], kommentar: false, dynamisch: false },
    ],
  },
  {
    datei: "src/components/DashboardStats.tsx",
    bereich: "geteilt",
    treffer: [
      { zeile: 9, literale: ["480 EUR"], kommentar: true, dynamisch: false },
    ],
  },
  {
    datei: "src/components/OnboardingGate.tsx",
    bereich: "geteilt",
    treffer: [
      { zeile: 486, literale: ["0 €"], kommentar: false, dynamisch: false },
    ],
  },
  {
    datei: "src/lib/__tests__/utils.test.ts",
    bereich: "test",
    treffer: [
      { zeile: 42, literale: ["25 €"], kommentar: false, dynamisch: true },
    ],
  },
  {
    datei: "src/lib/provider-registration.ts",
    bereich: "geteilt",
    treffer: [
      { zeile: 13, literale: ["10.000 €"], kommentar: true, dynamisch: false },
    ],
  },
  {
    datei: "src/lib/vertrag/vertrag-template.ts",
    bereich: "geteilt",
    treffer: [
      { zeile: 96, literale: ["1.234,50 €"], kommentar: true, dynamisch: false },
    ],
  },
  {
    datei: "src/modules/provider/dashboard.types.ts",
    bereich: "geteilt",
    treffer: [
      { zeile: 35, literale: ["0,00 €"], kommentar: true, dynamisch: false },
    ],
  },
] as const

/** Literale je Bereich, Kommentar-Treffer nicht mitgezaehlt. */
export const PREIS_AUDIT_SUMME = {
  redaktionell: { dateien: 6, literale: 1041, inKommentaren: 8 },
  oeffentlich: { dateien: 30, literale: 177, inKommentaren: 57 },
  test: { dateien: 13, literale: 8, inKommentaren: 17 },
  geteilt: { dateien: 10, literale: 7, inKommentaren: 9 },
  intern: { dateien: 5, literale: 6, inKommentaren: 3 },
  angemeldet: { dateien: 2, literale: 1, inKommentaren: 2 },
  api: { dateien: 11, literale: 0, inKommentaren: 15 },
  gesamt: 1240,
} as const

/**
 * Wie viele der OBEN GELISTETEN Dateien einen BUSINESS_DECISION_REQUIRED-
 * Marker tragen. Nicht die Gesamtzahl markierter Dateien im Repo: Marker
 * stehen auch dort, wo kein Waehrungszeichen im Quelltext steht — etwa in
 * `src/lib/constants.ts` (Preiskataloge als Zahlen ohne Einheit) und in
 * `src/lib/marketplace-rules.ts` (Provisionssaetze in Prozent).
 */
export const PREIS_AUDIT_MARKIERTE_DATEIEN = 26 as const
