#!/usr/bin/env bash
# status.sh — regeneriert STATUS.md im Repo-Root mit echtem Git/Vercel-Stand.
# Wird am Ende von deploy.sh aufgerufen. Kann jederzeit manuell laufen.

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
OUT="$REPO_ROOT/STATUS.md"

BRANCH=$(git rev-parse --abbrev-ref HEAD)
HEAD_HASH=$(git rev-parse HEAD)
HEAD_SHORT=$(git rev-parse --short HEAD)
LAST_MSG=$(git log -1 --pretty=%s)
LAST_AUTHOR=$(git log -1 --pretty='%an <%ae>')
LAST_DATE=$(git log -1 --pretty='%ad' --date=iso)
DIRTY_COUNT=$(git status --porcelain | wc -l | tr -d ' ')

# Sync gegen origin/main (best effort — fetch silently)
git fetch origin main --quiet 2>/dev/null || true
AHEAD=$(git rev-list --count origin/main..HEAD 2>/dev/null || echo "?")
BEHIND=$(git rev-list --count HEAD..origin/main 2>/dev/null || echo "?")

# Vercel — versuche project.json, sonst hartcoded
VERCEL_URL="https://chairmatch.de"
VERCEL_PROJECT=""
if [ -f "$REPO_ROOT/.vercel/project.json" ]; then
  VERCEL_PROJECT=$(grep -o '"projectId":"[^"]*"' "$REPO_ROOT/.vercel/project.json" | sed 's/"projectId":"\([^"]*\)"/\1/')
fi

VERCEL_STATUS_LINE="(kein VERCEL_TOKEN gesetzt — siehe Dashboard)"
VERCEL_DASHBOARD="https://vercel.com/team_iJXOJqpBTNdePfg1tMV0r1ip/chairmatch/deployments"
if [ -n "${VERCEL_TOKEN:-}" ] && command -v vercel >/dev/null 2>&1; then
  VERCEL_LATEST=$(vercel ls --token="$VERCEL_TOKEN" 2>/dev/null | head -20 || true)
  if [ -n "$VERCEL_LATEST" ]; then
    VERCEL_STATUS_LINE="$VERCEL_LATEST"
  fi
fi

TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S %Z')

# Letzte 5 commits (preformatted)
RECENT_COMMITS=$(git log --oneline -5)

cat > "$OUT" <<EOF
# STATUS.md — ChairMatch Repo & Deploy

_Generated by \`scripts/status.sh\` at **$TIMESTAMP**_

Dies ist die zentrale Wahrheits-Quelle für den aktuellen Stand.
**Nicht manuell editieren** — der Inhalt wird bei jedem \`./deploy.sh\` neu geschrieben.

---

## Git

| Feld | Wert |
|------|------|
| Branch | \`$BRANCH\` |
| HEAD | \`$HEAD_SHORT\` (\`$HEAD_HASH\`) |
| Letzter Commit | $LAST_MSG |
| Autor | $LAST_AUTHOR |
| Datum | $LAST_DATE |
| Uncommitted Changes | $DIRTY_COUNT |
| Ahead of origin/main | $AHEAD commits |
| Behind origin/main | $BEHIND commits |

### Letzte 5 Commits

\`\`\`
$RECENT_COMMITS
\`\`\`

---

## Vercel / Production

| Feld | Wert |
|------|------|
| Production URL | $VERCEL_URL |
| Project ID | ${VERCEL_PROJECT:-_unbekannt_} |
| Dashboard | $VERCEL_DASHBOARD |

### Latest Deployment

\`\`\`
$VERCEL_STATUS_LINE
\`\`\`

---

_Refresh: \`./scripts/status.sh\` — läuft automatisch am Ende von \`./deploy.sh\`._
EOF

echo "✓ STATUS.md updated ($TIMESTAMP)"
