/**
 * Ausführliche Guide-Inhalte für Stadt-Landing-Pages (/[stadt]).
 *
 * Ziel: 1500+ Wörter pro Stadtseite (SEO/GEO). Jede Stadt bekommt
 * 3 hand-geschriebene, EINZIGARTIGE Sektionen (~500-600 Wörter) —
 * kein Templating, um Duplicate-Content-Muster zu vermeiden.
 * Die programmatischen Sektionen (Ablauf, Berufsgruppen, Preisvergleich)
 * rendert page.tsx zusätzlich aus den CityData-Feldern.
 *
 * Städte ohne Guide (aktuell: Duisburg, Bochum, Wuppertal, Bielefeld,
 * Bonn, Münster) rendern die Sektion einfach nicht — fail-soft.
 */

export interface GuideSection {
  heading: string
  /** Absätze mit \n\n getrennt — page.tsx splittet und rendert <p> je Absatz. */
  text: string
}

export const CITY_GUIDES: Record<string, GuideSection[]> = {
  frankfurt: [
    {
      heading: 'Warum Frankfurt für Stuhlvermietung ein Ausnahme-Markt ist',
      text: 'Frankfurt am Main vereint auf engstem Raum, wofür andere Städte drei Bezirke brauchen: Banken-Klientel mit hohen Ansprüchen, ein internationales Messe-Publikum und eine wachsende Wohnbevölkerung in Vierteln wie Bornheim und dem Nordend. Für selbstständige Friseure, Barber und Kosmetikerinnen bedeutet das eine seltene Kombination — hohe Behandlungspreise bei gleichzeitig konstanter Nachfrage unter der Woche. Während in vielen Städten Dienstag und Mittwoch schwache Tage sind, buchen in Frankfurt Banker, Kanzlei-Angestellte und Consultants ihre Termine gezielt in die Mittagspause oder direkt nach Feierabend.\n\nDazu kommt der Flughafen-Effekt: Frankfurt hat eine überdurchschnittlich mobile, internationale Bevölkerung, die englischsprachigen Service aktiv sucht und Preise von 60 € aufwärts für einen guten Cut als normal empfindet. Wer einen Stuhl in Frankfurt mietet statt ein eigenes Ladenlokal zu eröffnen, spart sich die höchsten Gewerbemieten Hessens — und arbeitet trotzdem mitten in einem der kaufkräftigsten Einzugsgebiete Europas. Das Rhein-Main-Gebiet mit Offenbach, Bad Homburg, Eschborn und Darmstadt speist täglich Hunderttausende Pendler in die Stadt.',
    },
    {
      heading: 'Die richtige Lage: vom Bahnhofsviertel bis Bornheim',
      text: 'Das Bahnhofsviertel hat sich vom Problemkiez zum spannendsten Barber-Standort der Stadt entwickelt — hippe Shops, hohe Laufkundschaft, gute Erreichbarkeit. Wer hier einen Stuhl mietet, zahlt am oberen Ende der Spanne, profitiert aber von Frequenz, die sonst nur die Zeil bietet. Das Westend ist die Premium-Adresse für gehobene Kosmetik und Ästhetik: ruhige Straßen, Praxen-Nachbarschaft, Klientel mit geringer Preissensibilität.\n\nSachsenhausen funktioniert für etablierte Konzepte mit Stammkundschaft — der Stadtteil ist wohnlich, treu und weniger von Trends getrieben. Bornheim ("Bernem") mit der Berger Straße ist die beste Wahl für den Mittelweg: faire Mieten, dichte Wohnbevölkerung, starke Laufkundschaft am Wochenende. Nordend und Bockenheim ergänzen mit familiärer Klientel und Uni-Nähe. Faustregel für Frankfurt: Je näher an S-Bahn und Bürotürmen, desto wichtiger werden Online-Buchbarkeit und flexible Randzeiten — die Kundschaft plant hier spontan und digital.',
    },
    {
      heading: 'Praxis-Wissen für den Start in Frankfurt',
      text: 'Die Gewerbeanmeldung läuft über das Ordnungsamt der Stadt Frankfurt und kostet 30–60 €; Friseure benötigen den Eintrag in die Handwerksrolle der HWK Frankfurt-Rhein-Main, Kosmetik-, Nail- und Lash-Berufe sind zulassungsfrei. Kalkulatorisch solltest du in Frankfurt anders rechnen als im Bundesschnitt: Bei Stuhl-Mieten von 45–75 € pro Tag brauchst du Behandlungspreise im oberen Segment — und die Kundschaft zahlt sie, wenn Auftritt und Qualität stimmen. Ein Barber mit 8–10 Cuts am Tag zu 35–45 € liegt nach Miete bei 250–350 € Tagesgewinn.\n\nUnterschätzter Hebel: die Messe-Wochen. Buchmesse, Light+Building oder Automechanika bringen zehntausende Besucher in die Stadt — Studios in Messe- und Bahnhofsnähe verzeichnen in diesen Wochen spürbar mehr Walk-ins und kurzfristige Styling-Termine. Wer flexibel tageweise dazubucht, nimmt diese Spitzen mit, ohne sich langfristig zu binden. Genau dafür ist das Stuhl-Miet-Modell in Frankfurt ideal: Du skalierst deine Miettage mit deiner Auslastung, statt Fixkosten vorzufinanzieren.\n\nNoch ein Frankfurt-Spezifikum: die Zweisprachigkeit. Wer sein Profil und seine Buchungsseite konsequent auf Deutsch und Englisch führt, erschließt die Expat-Community der Banken und internationalen Kanzleien — eine Klientel mit hoher Zahlungsbereitschaft und geringer Wechselneigung, die von den meisten lokalen Anbietern schlicht nicht angesprochen wird.',
    },
  ],
  berlin: [
    {
      heading: 'Berlin: die Hauptstadt des Stuhl-Sharing',
      text: 'Nirgendwo in Deutschland ist das Stuhl-Miet-Modell so etabliert wie in Berlin. Über die Hälfte der Beauty-Profis der Hauptstadt arbeitet selbstständig — in gemieteten Stühlen, Kabinen und Shared Studios. Das hat den Markt geprägt: Salon-Betreiber sind an flexible Modelle gewöhnt, Verträge sind meist monatsweise kündbar, und niemand schaut komisch, wenn du nur dienstags bis donnerstags arbeitest. Für den Einstieg in die Selbstständigkeit ist Berlin damit die niedrigste Hürde unter den deutschen Metropolen.\n\nDie Kehrseite: Konkurrenz. In Neukölln oder Friedrichshain liegen teils drei Barbershops in einer Straße. Wer in Berlin besteht, tut das über Spezialisierung — Curly Hair, Balayage, Mega-Volume-Lashes, Skin Fades, Bart-Design. Generalisten haben es schwer, Spezialisten mit Instagram-Präsenz und klarer Zielgruppe füllen ihre Bücher dagegen erstaunlich schnell. Die niedrigen Stuhl-Mieten (ab 25 €/Tag) machen das Experimentieren risikolos: Ein Probemonat in einem neuen Kiez kostet weniger als anderswo eine Woche.',
    },
    {
      heading: 'Kiez-Logik: wo in Berlin dein Platz stehen sollte',
      text: 'Berlin funktioniert nicht als eine Stadt, sondern als Ansammlung von Kiezen — und deine Kundschaft wechselt den Kiez ungern. Mitte bedient Touristen, Startups und Agenturen: höchste Preise, aber auch höchste Fluktuation. Prenzlauer Berg ist der Familien- und Gutverdiener-Kiez mit treuer Stammkundschaft und stabilen Preisen. Neukölln (vor allem rund um Weserstraße und Schillerkiez) ist jung, international und beauty-affin — ideal für Lash, Brows und kreative Color-Arbeiten.\n\nFriedrichshain rund um Boxhagener Platz zieht ein ähnliches Publikum mit etwas mehr Kaufkraft. Kreuzberg bleibt der Barber-Hotspot mit internationaler Walk-in-Kundschaft. Charlottenburg wird oft unterschätzt: Die City West hat die zahlungskräftigste ältere Klientel der Stadt und deutlich weniger Konkurrenz-Dichte als der Osten. Wedding schließlich ist der Geheimtipp für den günstigen Start — die Gentrifizierung läuft, die Mieten sind noch niedrig, und wer jetzt Stammkundschaft aufbaut, wächst mit dem Kiez.',
    },
    {
      heading: 'Rechnen und starten: so gelingt der Einstieg in Berlin',
      text: 'Die Gewerbeanmeldung kostet in Berlin 26 € und läuft komplett online über service.berlin.de. Friseure brauchen den Meisterbrief oder eine Ausübungsberechtigung nach § 7b Handwerksordnung (sechs Jahre Berufserfahrung, davon vier in leitender Stellung) — ein Weg, den viele Berliner Selbstständige gegangen sind. Kosmetik, Nails, Lashes und Make-up sind zulassungsfrei.\n\nKalkulatorisch ist Berlin ein Volumen-Markt: Behandlungspreise liegen 20–30 % unter München, die Stuhl-Miete aber 50 % darunter. Mit 25–40 € Tagesmiete bist du ab dem zweiten Kunden profitabel. Realistisch sind 80–150 € Tagesgewinn in der Breite, 200 €+ mit Spezialisierung in guten Kiezen. Wichtigster Praxis-Tipp: Baue deine Instagram-Präsenz VOR dem Umzug in einen neuen Kiez auf und kündige den Standort an — Berliner Kundschaft folgt Profilen, nicht Ladenschildern. Und nutze die Flexibilität des Modells: Viele erfolgreiche Berliner Profis mieten zwei Standorte in verschiedenen Kiezen und bedienen zwei Zielgruppen parallel.\n\nZuletzt der Blick auf den Kalender: Berlin lebt von Events. Fashion Week, Berlinale, die Festival-Sommer und die Silvester-Wochen erzeugen planbare Nachfrage-Spitzen für Styling, Make-up und Nails. Wer sein Miet-Modell flexibel hält und zu diesen Terminen Zusatztage bucht, verwandelt die Event-Frequenz der Hauptstadt direkt in Umsatz — ohne sich das restliche Jahr an hohe Fixkosten zu binden.',
    },
  ],
  muenchen: [
    {
      heading: 'München: der profitabelste Beauty-Markt Deutschlands',
      text: 'München ist teuer — für Salon-Betreiber, für Mieter, für alle. Aber genau deshalb funktioniert Stuhlvermietung hier so gut: Ein eigenes Ladenlokal in der Maxvorstadt oder Schwabing ist für Einzelkämpfer praktisch unbezahlbar, ein gemieteter Stuhl dagegen ab 55 €/Tag zu haben. Die Rechnung geht auf, weil die Münchner Kundschaft die höchsten Behandlungspreise der Republik akzeptiert: 60–90 € für einen Damenhaarschnitt, 120–180 € für Volume-Lashes, 45–60 € für einen Barber-Cut sind Stadtstandard, nicht Premium.\n\nDie Klientel ist anspruchsvoll und erwartet Perfektion — vom ersten Instagram-Eindruck über die Terminbestätigung bis zum Nachsorge-Tipp. Wer diese Erwartung bedient, wird mit einer Loyalität belohnt, die ihresgleichen sucht: Münchner Kundschaft bleibt oft Jahre und bringt aktiv Empfehlungen. Der Markt verzeiht allerdings wenig; unpünktliche oder unverbindliche Anbieter sortiert er schnell aus. München ist kein Einsteiger-Markt, aber für erfahrene Profis der lukrativste Standort Deutschlands.',
    },
    {
      heading: 'Von Maxvorstadt bis Giesing: Münchens Beauty-Landkarte',
      text: 'Die Maxvorstadt ist das Zentrum der gehobenen Beauty-Szene — zwischen Pinakotheken und Universität sitzen Studios mit internationalem Anspruch und Preisen am oberen Ende. Schwabing bleibt der Klassiker: flanierfreudige, zahlungskräftige Kundschaft rund um Hohenzollern- und Leopoldstraße. Das Glockenbachviertel bedient die junge, trendbewusste Zielgruppe und ist der stärkste Standort für Barber und ausgefallene Color-Konzepte.\n\nHaidhausen ("Franzosenviertel") kombiniert Altbau-Charme mit treuer Wohn-Kundschaft — ideal für Kosmetik und Nails mit Termingeschäft. Neuhausen wächst mit dem Arnulfpark und bietet noch faire Einstiegsmieten bei solider Kaufkraft. Wer es rechnerisch angehen will: Giesing und Sendling liegen preislich 20–30 % unter den Szenevierteln, die S- und U-Bahn bringt Kundschaft trotzdem in 15 Minuten überall hin. Generell gilt in München mehr als anderswo: Die Adresse ist Teil des Markenversprechens — ein Stuhl in einem hochwertigen Studio in guter Lage rechtfertigt allein schon höhere Preise.',
    },
    {
      heading: 'Warteliste, NiSV, Kalkulation: Praxis-Tipps für München',
      text: 'Plane in München Vorlauf ein: Die begehrten Studios in Maxvorstadt, Schwabing und Glockenbach führen Wartelisten, 4–8 Wochen bis zum passenden Platz sind normal. Nutze die Zeit für den Papierkram: Gewerbeanmeldung beim Kreisverwaltungsreferat (rund 50 €), Handwerksrollen-Eintrag für Friseure bei der HWK München und Oberbayern, und — wichtig für apparative Kosmetik — die NiSV-Fachkunde, ohne die Laser-, IPL- und Ultraschall-Behandlungen nicht erlaubt sind. Bayern kontrolliert das konsequent.\n\nKalkulatorisch trägt sich ein Münchner Stuhl ab etwa drei Kunden pro Tag; ab fünf wird es sehr komfortabel. Bei 70 € Tagesmiete und Münchner Behandlungspreisen sind 150–250 € Tagesgewinn die realistische Mitte, Spitzenkräfte mit voller Auslastung liegen deutlich darüber. Ein München-spezifischer Tipp: Firmenkooperationen lohnen sich hier wie nirgends. Die Konzernzentralen von BMW, Allianz, Siemens und Co. sind voller Menschen mit wenig Zeit und viel Budget — wer über Corporate-Benefits-Programme oder schlicht gute Google-Sichtbarkeit im Büro-Umfeld gefunden wird, füllt seine Mittagsslots von selbst.\n\nUnd natürlich das Oktoberfest: Die Wiesn-Wochen sind für Münchens Beauty-Branche Hochsaison — Dirndl-Frisuren, Braid-Styling, Make-up und Last-Minute-Termine treiben die Nachfrage ab Mitte September massiv nach oben. Viele Selbstständige buchen für diese Zeit gezielt Zusatztage und erwirtschaften in zwei Wiesn-Wochen einen spürbaren Teil ihres Quartalsumsatzes.',
    },
  ],
  hamburg: [
    {
      heading: 'Hamburg: Qualität schlägt Trend',
      text: 'Der Hamburger Beauty-Markt tickt hanseatisch: Man wechselt nicht ständig den Anbieter, man leistet sich Qualität — und bleibt dann. Für Stuhl-Mieter ist das die vielleicht wichtigste Eigenschaft des Marktes. Der Aufbau eines Kundenstamms dauert hier etwas länger als in Berlin, dafür ist er danach außergewöhnlich stabil: Wiederkehr-Raten von 70–80 % sind in etablierten Hamburger Studios keine Seltenheit. Die Stadt belohnt Handwerk und Verlässlichkeit stärker als Hype.\n\nWirtschaftlich steht Hamburg auf breitem Fundament — Hafen, Medien, Handel, Versicherungen — und die Beauty-Nachfrage schwankt entsprechend wenig. Auffällig ist die hohe Akzeptanz des Stuhl-Miet-Modells bei den Salon-Betreibern selbst: Viele Inhaber haben erkannt, dass ein vermieteter Stuhl planbarer ist als eine schwer zu findende Festanstellung, und bieten aktiv Plätze mit fairen Wochen- und Monatspaketen an. Die Auswahl an verfügbaren Plätzen ist dadurch besser als in den meisten Großstädten — gute Verhandlungsposition für Mieter.',
    },
    {
      heading: 'Schanze, Eppendorf, HafenCity: Lagen mit eigenem Charakter',
      text: 'Die Sternschanze ist Hamburgs kreatives Zentrum — jung, dicht, beauty-affin. Barber, Lash-Studios und Concept-Salons profitieren hier von Lauf- und Szene-Kundschaft gleichermaßen; die Mieten liegen im oberen Mittelfeld. Eimsbüttel dahinter ist der Wohnviertel-Klassiker: Osterstraße und Umgebung liefern treue Stammkundschaft mit solider Kaufkraft, ideal für Friseur- und Kosmetik-Konzepte mit Termingeschäft.\n\nEppendorf und Winterhude sind die Premium-Adressen — gehobene Klientel, höchste Behandlungspreise der Stadt, aber auch Erwartungen an entsprechendes Ambiente. St. Pauli und Altona bedienen ein bunteres Publikum mit starker Abend- und Wochenendfrequenz. Die HafenCity schließlich ist Hamburgs jüngstes Quartier: viel Büro-Publikum, das Termine in Mittagspause und Feierabend legt, kaum gewachsene Konkurrenz — wer früh dort ist, besetzt eine Lücke. Für die Wahl gilt: Hamburgs Kundschaft ist stadtteiltreu. Miete deinen Stuhl dort, wo deine Zielgruppe wohnt oder arbeitet, nicht wo die Miete am niedrigsten ist.',
    },
    {
      heading: 'Pakete, Anmeldung, Aufbau: so startest du in Hamburg',
      text: 'Hamburg macht den Verwaltungsteil einfach: Die Gewerbeanmeldung läuft digital über Hamburg Service, kostet rund 20 € und ist meist binnen einer Woche erledigt. Friseure weisen den Meisterbrief oder eine Ausübungsberechtigung nach, Kosmetik-, Nail- und Lash-Berufe starten zulassungsfrei. Das Gesundheitsamt erwartet einen Hygieneplan nach Hamburger Hygieneverordnung — Standard, aber er sollte schriftlich vorliegen.\n\nDie Hamburger Besonderheit sind die Miet-Pakete: 3-Tage- und 5-Tage-Wochenmodelle mit 10–25 % Rabatt gegenüber Tagesbuchung sind hier verbreiteter als anderswo. Für den Aufbau lohnt der Mittelweg — zwei bis drei feste Tage als Basis, dazu flexible Einzeltage bei hoher Nachfrage. Kalkulatorisch liegt Hamburg angenehm: Bei 40–65 € Tagesmiete und stabilen Behandlungspreisen (Damenhaarschnitt 50–75 €, Gesichtsbehandlung 60–90 €) trägt sich der Platz ab dem dritten Kunden. Und ein Hamburg-Tipp zum Schluss: Das Umland zahlt mit. Kundschaft aus Norderstedt, Pinneberg und Ahrensburg pendelt selbstverständlich zu guten Spezialisten in die Stadt — Profile mit klarer Spezialisierung ziehen dieses Einzugsgebiet von über drei Millionen Menschen an.\n\nSaisonal lohnt der Blick auf Hamburgs Event-Kalender: Hafengeburtstag, Cruise Days und die Vorweihnachtszeit bringen Frequenz in die Innenstadt-Lagen, und die Hochzeits-Saison von Mai bis September füllt bei Stylist:innen und Make-up-Artists die Wochenenden Monate im Voraus. Wer diese Spitzen mit flexiblen Zusatztagen mitnimmt, glättet die ruhigeren Wintermonate mühelos.',
    },
  ],
  koeln: [
    {
      heading: 'Köln: der zugänglichste Metropol-Markt für den Einstieg',
      text: 'Köln hat unter Deutschlands Millionenstädten die niedrigste Einstiegshürde für Beauty-Selbstständige — nicht wegen der Preise allein, sondern wegen der Mentalität. Die Kölner Kundschaft probiert gern Neues aus, empfiehlt aktiv weiter und verzeiht Anfangs-Holprigkeit, wenn die Persönlichkeit stimmt. Wo Münchner Klientel Perfektion erwartet, honoriert die Kölner Nähe und Authentizität. Für den ersten Schritt in die Selbstständigkeit ist das Gold wert: Der Kundenstamm wächst hier über Mundpropaganda schneller als über jedes Marketing-Budget.\n\nDer Markt selbst ist in Bewegung: Lash & Brows und Nageldesign wachsen in Köln überdurchschnittlich, die Barber-Szene rund um Ehrenfeld und das Belgische Viertel gehört zu den lebendigsten des Landes. Salon-Betreiber kennen und nutzen das Stuhl-Miet-Modell breit, die Tagespreise (35–60 € für einen Friseurstuhl) liegen fair im Mittelfeld. Und mit Bonn, Leverkusen und dem Bergischen Land vor der Tür bedient ein guter Kölner Standort ein Einzugsgebiet von weit über zwei Millionen Menschen.',
    },
    {
      heading: 'Veedel-Wissen: Ehrenfeld, Belgisches Viertel, Südstadt & Co.',
      text: 'Köln denkt in Veedeln, und jedes hat sein eigenes Beauty-Profil. Ehrenfeld ist das kreative Kraftzentrum: junge Zielgruppe, dichte Studio-Szene, die höchste Lash- und Barber-Dichte der Stadt — wer hier gut ist, wird schnell sichtbar. Das Belgische Viertel ist die Style-Adresse mit modischer Laufkundschaft und Preisen am oberen Ende. Die Südstadt lebt von treuer, wohnlicher Stammkundschaft, die Wert auf persönliche Bindung legt.\n\nNippes ist der aufstrebende Geheimtipp: noch faire Mieten, wachsende junge Bevölkerung, gute Bahn-Anbindung. Lindenthal bedient mit Uniklinik-Nähe und gehobener Wohnlage die kaufkräftigere Kosmetik-Klientel, Rodenkirchen die ruhige Premium-Kundschaft am Rhein. Die Innenstadt zwischen Schildergasse und Friesenplatz liefert maximale Laufkundschaft, aber auch die höchsten Mieten und die meiste Konkurrenz. Praktische Faustregel: Für Termingeschäft (Lash, Kosmetik, Color) sind die Wohnveedel die bessere Wahl; für Walk-in-Geschäft (Barber, Blowout) zählt Frequenz — Innenstadt, Ehrenfelder Hauptachsen oder Zülpicher Viertel.',
    },
    {
      heading: 'Vom Papierkram bis Karneval: Praxis-Tipps für Köln',
      text: 'Die Formalitäten sind überschaubar: Gewerbeanmeldung beim Amt für öffentliche Ordnung (rund 26 €, online möglich), Handwerksrollen-Eintrag für Friseure bei der HWK zu Köln, zulassungsfreier Start für Kosmetik, Nails und Lashes. Die Hygiene-Anforderungen des Gesundheitsamts entsprechen dem NRW-Standard — Hygieneplan, Instrumenten-Desinfektion, bei apparativer Kosmetik die NiSV-Fachkunde.\n\nKalkulatorisch ist Köln dankbar: Bei 35–60 € Tagesmiete trägt sich der Stuhl ab dem zweiten bis dritten Kunden. Realistisch sind 120–220 € Tagesgewinn für etablierte Profis, in Premium-Lagen mehr. Und dann ist da der Kölner Kalender: Karneval ist für die Beauty-Branche ein echter Wirtschaftsfaktor — die Wochen vor Weiberfastnacht sind mit Styling-, Make-up- und Nail-Terminen regelmäßig ausgebucht, viele Selbstständige machen im Februar ihren stärksten Monat. Auch die Session-Eröffnung im November und die großen Messen (gamescom, Art Cologne) bringen planbare Nachfrage-Spitzen. Wer sein Miet-Modell flexibel hält und zu diesen Zeiten Tage dazubucht, nimmt die Spitzen voll mit — genau dafür ist tageweise Stuhlmiete gemacht.\n\nFür den langfristigen Aufbau zählt in Köln vor allem eines: Präsenz im Veedel. Empfehlungen laufen hier über Nachbarschaft, Stammkneipe und Vereinsleben — wer sich lokal zeigt, mit umliegenden Geschäften kooperiert und seine Google-Bewertungen pflegt, wächst schneller als über jede bezahlte Anzeige. Die Kölner Devise "man kennt sich" ist im Beauty-Geschäft bare Münze.',
    },
  ],
  duesseldorf: [
    {
      heading: 'Düsseldorf: Mode-Kapital und Premium-Beauty-Markt',
      text: 'Düsseldorf ist die Stadt, in der Beauty zum Selbstverständnis gehört: Modehandel, Agenturen, Kanzleien und Konzernzentralen haben eine Klientel geformt, die gepflegtes Auftreten als Berufsvoraussetzung versteht — und entsprechend regelmäßig und hochwertig bucht. Rund um die Königsallee haben sich Behandlungspreise etabliert, die nur München übertrifft: 70–100 € für einen Damenhaarschnitt, 90–140 € für gehobene Gesichtsbehandlungen sind in Top-Lagen normal.\n\nFür Stuhl-Mieter ist Düsseldorf doppelt interessant: Die Tagesmieten (40–70 €) liegen spürbar unter dem Münchner Niveau, die erzielbaren Preise aber nur knapp darunter — die Marge pro Arbeitstag gehört damit zu den besten in Deutschland. Dazu kommt die internationale Dimension: Das Japanviertel an der Immermannstraße ist einzigartig in Europa, und die japanische wie zunehmend koreanische Community bringt eine stilbewusste Kundschaft mit spezifischen Bedürfnissen (Haar-Texturen, Skin-Care-Kultur), die spezialisierte Anbieter gezielt sucht. Wer hier Expertise mitbringt, besetzt eine Nische mit sehr loyaler Klientel.',
    },
    {
      heading: 'Kö-Glanz und Flingern-Charme: die Standort-Frage',
      text: 'Die Stadtmitte rund um Kö und Schadowstraße liefert maximale Sichtbarkeit und die zahlungskräftigste Laufkundschaft — zu entsprechenden Mieten. Oberkassel auf der linken Rheinseite ist die diskrete Premium-Alternative: alteingesessene, sehr kaufkräftige Wohnklientel, die Wert auf Beständigkeit legt. Pempelfort trifft die Mitte — zentral, wohnlich, mit treuer Stammkundschaft und fairen Preisen.\n\nFlingern ist Düsseldorfs Kreativviertel und der spannendste Standort für junge Konzepte: In den Ladenlokalen rund um Ackerstraße und Hermannplatz entstehen Studios, die Lash, Brows, Nails und Barbering mit Szene-Anschluss verbinden — die Mieten liegen 30–40 % unter der Stadtmitte. Bilk punktet mit Uni-Nähe und jungem Publikum, Derendorf mit Messe-Anbindung. Ein Düsseldorf-spezifischer Faktor: die Messe. Beauty Düsseldorf, TOP HAIR und die großen Fachmessen bringen nicht nur Besucher, sondern die Branche selbst in die Stadt — Networking, Fortbildung und Sichtbarkeit inklusive. Studios in Messe-Nähe spüren diese Wochen deutlich im Kalender.',
    },
    {
      heading: 'So rechnet sich Düsseldorf für Selbstständige',
      text: 'Der administrative Start ist NRW-Standard: Gewerbeanmeldung beim Amt für Verbraucherschutz und Gewerbe (ca. 26 €), Handwerksrolle für Friseure über die HWK Düsseldorf, zulassungsfreier Start für Kosmetik- und Nail-Berufe. Bei apparativer Kosmetik (IPL, Laser, Radiofrequenz) verlangt auch NRW die NiSV-Fachkunde — in der Ästhetik-affinen Düsseldorfer Kundschaft ein wachsendes Geschäftsfeld, das die Investition schnell zurückzahlt.\n\nKalkulatorisch führt in Düsseldorf der Premium-Weg: Statt über Volumen zu gehen, lohnt es sich, Positionierung und Preisniveau von Anfang an hoch anzusetzen. Ein Beispiel: Eine Lash-Stylistin mit 70 €-Kabine in Pempelfort und vier Volume-Terminen à 130 € liegt bei über 400 € Tagesgewinn — in Flingern mit günstigerer Kabine und jüngerer Kundschaft funktioniert dieselbe Rechnung über fünf bis sechs Termine im 90-€-Segment. Der wichtigste Praxis-Tipp: Düsseldorfer Kundschaft bucht über Empfehlung und gepflegte Online-Präsenz; ein professionelles Portfolio und konsistente Google-Bewertungen wirken hier stärker als Rabatt-Aktionen, die im Premium-Umfeld eher Misstrauen wecken.',
    },
  ],
  stuttgart: [
    {
      heading: 'Stuttgart: solide Kaufkraft im Talkessel',
      text: 'Stuttgart ist der Markt für Planer: Die Region hat mit Automobilindustrie, Maschinenbau und Zulieferern eine der höchsten Kaufkraftdichten Europas, und die Beauty-Nachfrage ist entsprechend stabil und wenig trend-getrieben. Die Kundschaft bucht regelmäßig, zahlt zuverlässig gute Preise und bleibt bei Anbietern, die konstante Qualität liefern. Volatilität, wie sie Berlin oder Leipzig kennen, gibt es hier kaum — dafür auch weniger Hype-Effekte. Wer verlässliches Einkommen der schnellen Skalierung vorzieht, ist in Stuttgart richtig.\n\nDie Besonderheit des Marktes ist die Flächenknappheit: Der Talkessel begrenzt das Angebot an Gewerbeflächen physisch, Leerstand existiert praktisch nicht, und ein eigenes Ladenlokal ist für Einzelkämpfer kaum realistisch. Genau das macht Stuhlvermietung in Stuttgart zum logischen Modell — Salon-Betreiber monetarisieren ungenutzte Plätze, Selbstständige umgehen die aussichtslose Ladensuche. Die Tagesmieten (45–70 € für einen Stuhl) spiegeln die Knappheit, werden aber von den erzielbaren Behandlungspreisen gut getragen.',
    },
    {
      heading: 'Vom Kessel bis auf die Fildern: Standorte in Stuttgart',
      text: 'Stuttgart-Mitte rund um Königstraße und Marienplatz bündelt Laufkundschaft, Büro-Publikum und die beste ÖPNV-Erreichbarkeit — erste Wahl für Barber und Walk-in-Konzepte. Der Stuttgarter Westen ist das dichteste Wohnviertel der Stadt und ein Klassiker für Termingeschäft: Kosmetik, Color-Spezialisten und Nail-Studios leben hier von einer treuen, gut situierten Nachbarschafts-Kundschaft.\n\nDegerloch oben auf den Fildern bedient die gehobene Klientel der Halbhöhenlagen, Bad Cannstatt liefert als bevölkerungsreichster Bezirk solide Nachfrage zu moderateren Mieten, und Vaihingen profitiert von Uni-Campus und Gewerbegebieten mit Mittagspausen-Publikum. Der entscheidende Standort-Faktor ist in Stuttgart aber die Pendler-Logik: Hunderttausende pendeln täglich per S-Bahn und Stadtbahn durch den Kessel, und Beauty-Termine werden bevorzugt auf den Arbeitsweg gelegt. Ein Stuhl in Haltestellen-Nähe mit Abend-Slots bis 20 Uhr schlägt in der Auslastung fast jede andere Lage-Eigenschaft — das unterscheidet Stuttgart von Flanier-Städten wie Köln oder Düsseldorf.',
    },
    {
      heading: 'Start-Wissen für Stuttgart: Anmeldung, Vorlauf, Kalkulation',
      text: 'Die Gewerbeanmeldung läuft über das Amt für öffentliche Ordnung, digital via service-bw, und kostet 40–60 €. Friseure tragen sich bei der Handwerkskammer Region Stuttgart in die Handwerksrolle ein; Kosmetik, Nails und Lashes sind zulassungsfrei. Baden-Württemberg prüft Hygiene-Standards gewissenhaft — ein dokumentierter Hygieneplan gehört zur Grundausstattung.\n\nWegen der Flächenknappheit gilt: Vorlauf einplanen. In zentralen Lagen sind 3–5 Wochen bis zum passenden Platz normal, in Stadtteilzentren geht es schneller. Kalkulatorisch trägt die Stuttgarter Kaufkraft: Bei 45–70 € Tagesmiete und Behandlungspreisen von 45–70 € (Herren-Cut mit Styling) bis 90–130 € (Färbe-Services) liegt der Break-even beim zweiten bis dritten Kunden; 150–280 € Tagesgewinn sind für etablierte Profis die realistische Spanne. Ein Stuttgart-Tipp: Die umliegenden Zentren — Ludwigsburg, Esslingen, Böblingen — haben kaufkräftige Bevölkerung, aber wenig spezialisierte Studios. Wer sich in Stuttgart-Mitte auf gefragte Nischen (Balayage, PMU, Mega-Volume) positioniert, zieht Kundschaft aus der gesamten Region, die für Qualität selbstverständlich 30 Minuten S-Bahn fährt.',
    },
  ],
  hannover: [
    {
      heading: 'Hannover: der unterschätzte stabile Markt',
      text: 'Hannover taucht selten in Beauty-Trend-Reports auf — und genau das ist seine Stärke. Die niedersächsische Landeshauptstadt bietet eine Kombination, die Gründer unterschätzen: moderate Stuhl-Mieten (30–55 €/Tag), eine loyale Stammkundschaft und breite, konjunkturstabile Nachfrage durch Verwaltung, Versicherungen (Hannover ist einer der größten Versicherungsstandorte Europas), Universität und Medizinische Hochschule. Wer hier Qualität liefert, baut sich einen Kundenstamm auf, der über Jahre bleibt — die Fluktuation gehört zu den niedrigsten unter den deutschen Großstädten.\n\nDie Konkurrenzdichte ist gleichzeitig deutlich geringer als in den Metropolen: Spezialisierte Angebote wie Mega-Volume-Lashes, Balayage-Expertise oder modernes Barbering sind in Hannover noch rar und werden schnell sichtbar. Der Weg von der ersten Woche zum vollen Terminkalender ist hier oft kürzer als in übersättigten Märkten wie Berlin-Neukölln — bei etwa der Hälfte der Fixkosten. Für den planbaren, risikoarmen Aufbau einer Selbstständigkeit gehört Hannover zu den besten Standorten Deutschlands.',
    },
    {
      heading: 'List, Linden, Mitte: Hannovers Beauty-Geografie',
      text: 'Die List ist Hannovers Wohnviertel-Klassiker — dicht besiedelt, bürgerlich, mit der treuesten Stammkundschaft der Stadt. Kosmetik-Institute und Friseur-Konzepte mit Termingeschäft finden hier ihr ideales Umfeld; die Lister Meile ist zugleich Einkaufsstraße mit ordentlicher Laufkundschaft. Linden ist der Gegenpol: jung, kreativ, multikulturell — der Limmer Straße-Kiez trägt Barbershops, Lash-Studios und ausgefallene Konzepte, die anderswo in der Stadt kein Publikum fänden.\n\nMitte bündelt Laufkundschaft rund um Kröpcke und Ernst-August-Platz und profitiert als einziger Standort spürbar vom Messe-Kalender. Die Südstadt ist ruhig und solide, Bothfeld und die Oststadt ergänzen mit familiärer Nachbarschafts-Klientel. Ein Hannover-Faktum, das Standort-Entscheidungen prägen sollte: Das Einzugsgebiet ist größer als die Stadt. Aus Langenhagen, Laatzen, Garbsen und dem Umland — zusammen über eine Million Menschen in der Region — pendelt Kundschaft selbstverständlich zu guten Spezialisten in die Stadt, denn spezialisierte Studios gibt es außerhalb kaum. Gute Parkmöglichkeiten oder Stadtbahn-Nähe sind deshalb ein echtes Buchungsargument.',
    },
    {
      heading: 'Messe-Rhythmus und Aufbau-Strategie in Hannover',
      text: 'Der Verwaltungsstart ist unkompliziert: Gewerbeanmeldung beim Fachbereich Öffentliche Ordnung (30–40 €), Handwerksrolle für Friseure bei der HWK Hannover, zulassungsfreier Beginn für Kosmetik-, Nail- und Lash-Berufe. Die Hygiene-Anforderungen folgen der niedersächsischen Verordnung — Standard-Hygieneplan genügt.\n\nHannovers Eigenheit ist der Messe-Rhythmus: Hannover Messe, Agritechnica, IdeenExpo und weitere Großveranstaltungen bringen mehrfach im Jahr zehntausende Gäste in die Stadt. Für Studios in Mitte und Oststadt bedeutet das planbare Nachfrage-Spitzen bei Styling-, Barber- und Express-Terminen — wer tageweise flexibel dazubuchen kann, verwandelt Messe-Wochen in Umsatz-Rekorde. Kalkulatorisch ist Hannover entspannt: Bei 30–55 € Tagesmiete trägt sich der Platz ab dem zweiten Kunden, und 100–180 € Tagesgewinn sind solide erreichbar. Der wichtigste Aufbau-Tipp für Hannover: Setze auf Google-Bewertungen und lokale Sichtbarkeit statt auf Instagram-Hype. Die hannoversche Kundschaft recherchiert gründlich, liest Rezensionen und bleibt dann — der Vertrauensaufbau läuft hier über Verlässlichkeit, nicht über Ästhetik-Feeds.',
    },
  ],
  nuernberg: [
    {
      heading: 'Nürnberg: fränkische Kaufkraft ohne München-Preise',
      text: 'Nürnberg ist die wirtschaftliche Hauptstadt Frankens und für Beauty-Selbstständige ein rechnerischer Glücksfall: Die Behandlungspreise liegen nur 10–20 % unter dem Münchner Niveau, die Stuhl-Mieten aber 35–40 % darunter. Die Marge pro Arbeitstag gehört damit zu den besten in Bayern. Getragen wird der Markt von einer soliden Wirtschaftsstruktur — Siemens, Datev, adidas und Puma im Umland, dazu Versicherungen und ein starker Mittelstand — und von der fränkischen Mentalität: Man bleibt seinem Friseur treu, wenn er sein Handwerk versteht.\n\nDie Metropolregion ist der stille Multiplikator: Fürth ist per U-Bahn in zehn Minuten erreichbar, Erlangen mit Siemens Healthineers und Universität in zwanzig — zusammen ein Einzugsgebiet von rund 1,3 Millionen Menschen mit überdurchschnittlichen Einkommen. Spezialisierte Angebote, die es in Fürth oder Erlangen nicht gibt, ziehen diese Kundschaft automatisch nach Nürnberg. Wer bayerische Kaufkraft sucht, ohne Münchner Fixkosten und Wartelisten zu akzeptieren, findet in Nürnberg den logischen Standort.',
    },
    {
      heading: 'GoHo, Altstadt, St. Johannis: wo Nürnberg bucht',
      text: 'Gostenhof — liebevoll "GoHo" — ist Nürnbergs Antwort auf Berlin-Kreuzberg: Galerien, Cafés und eine junge Studio-Szene in ehemaligen Handwerker-Höfen. Barbershops, Brow-Bars und kreative Color-Konzepte finden hier ihr Publikum, die Szene empfiehlt sich gegenseitig weiter, und die Mieten sind noch moderat. Die Altstadt rund um St. Lorenz und die Fußgängerzone liefert die höchste Laufkundschaft Frankens, verstärkt durch Touristen — ideal für Walk-in-Geschäft, zu entsprechend höheren Mieten.\n\nSt. Johannis ist die gehobene Wohnlage: Altbauten, etablierte Kosmetik-Institute, zahlungskräftige Klientel mit Termintreue. Maxfeld und Wöhrd ergänzen mit ruhiger Nachbarschafts-Kundschaft, die Südstadt ist der günstige, multikulturell geprägte Einstiegsstandort mit starker Barber-Nachfrage. Für die Standortwahl gilt in Nürnberg eine einfache Logik: Terminbasierte Premium-Services (Kosmetik, PMU, Lashes) gehören nach St. Johannis oder Maxfeld, junge Trend-Konzepte nach GoHo, Volumen-Geschäft in die Altstadt oder Südstadt. Die kurzen Wege der Stadt — fast alles liegt im 20-Minuten-Radius — machen auch Zweit-Standort-Modelle unkompliziert.',
    },
    {
      heading: 'Praktisch starten in Nürnberg',
      text: 'Der Verwaltungsweg ist bayerisch-gründlich, aber berechenbar: Gewerbeanmeldung beim Ordnungsamt der Stadt Nürnberg (rund 40 €), Handwerksrollen-Eintrag für Friseure bei der HWK für Mittelfranken, zulassungsfreier Start für Kosmetik, Nails und Lashes. Bayern kontrolliert Hygiene und NiSV-Vorgaben konsequent: Wer apparative Kosmetik (IPL, Laser, Radiofrequenz) anbietet, braucht die Fachkunde-Nachweise, und ein schriftlicher Hygieneplan mit VAH-konformer Desinfektion sollte selbstverständlich sein — dann verlaufen Kontrollen problemlos.\n\nKalkulatorisch trägt sich ein Nürnberger Stuhl schnell: Bei 35–55 € Tagesmiete und fränkischen Behandlungspreisen (Herren-Cut 30–42 €, Damen-Cut 50–70 €, Volume-Lashes 100–140 €) liegt der Break-even beim zweiten bis dritten Kunden; 130–230 € Tagesgewinn sind die realistische Mitte. Zwei Nürnberg-spezifische Chancen zum Schluss: Der Christkindlesmarkt bringt im Dezember Touristen-Frequenz in die Altstadt, von der Styling- und Barber-Angebote direkt profitieren. Und die Consumenta sowie weitere Messen am Messezentrum sorgen für planbare Zusatznachfrage — tageweise Stuhl-Miete macht es leicht, diese Spitzen gezielt mitzunehmen.',
    },
  ],
  leipzig: [
    {
      heading: 'Leipzig: der Wachstumsmarkt für mutige Gründer',
      text: '"Hypezig" ist mehr als ein Spitzname: Leipzig wächst seit Jahren schneller als fast jede andere deutsche Großstadt, und die Zuziehenden sind jung, kreativ und beauty-affin. Für Selbstständige entsteht daraus eine seltene Marktlage — wachsende Nachfrage trifft auf ein noch nicht gesättigtes Angebot. Während in München oder Köln jede Nische besetzt ist, gibt es in Leipzig noch echte Lücken: Spezialisierte Brow-Artists, Curly-Hair-Experten oder moderne Barber-Konzepte finden hier binnen Wochen ihr Publikum.\n\nDie Einstiegskosten verstärken den Effekt: Mit Stuhl-Mieten ab 25 €/Tag gehört Leipzig zu den günstigsten Großstadt-Märkten, während die Behandlungspreise durch die steigende Kaufkraft kontinuierlich anziehen — die Schere öffnet sich zugunsten der Selbstständigen. Wer heute in Plagwitz oder der Südvorstadt einen Stuhl mietet und Stammkundschaft aufbaut, wächst mit einem Markt, der seine beste Phase noch vor sich hat. Das Risiko ist dabei minimal: Ein voller Miet-Monat kostet hier weniger als eine Woche in Münchner Top-Lage.',
    },
    {
      heading: 'Plagwitz, Karli, Connewitz: Leipzigs Szene-Standorte',
      text: 'Plagwitz ist das Aushängeschild des neuen Leipzig: In den umgenutzten Industriebauten entlang der Karl-Heine-Straße sitzen Ateliers, Agenturen und eine wachsende Studio-Szene — das Publikum ist jung, gestaltungsaffin und probierfreudig. Die Südvorstadt entlang der Karl-Liebknecht-Straße ("Karli") ist die belebteste Ausgeh-Meile der Stadt und trägt Barber-, Styling- und Lash-Konzepte mit starker Abend- und Wochenendfrequenz.\n\nConnewitz bleibt das alternative Herz Leipzigs — wer hier arbeitet, bedient eine eingeschworene Szene-Kundschaft, die Wert auf Authentizität legt und sehr loyal bleibt. Das Zentrum liefert klassische Laufkundschaft rund um Grimmaische Straße und Hauptbahnhof, Gohlis die bürgerliche Stammkundschaft im Norden. Reudnitz und Lindenau sind die Geheimtipps für den günstigsten Einstieg — beide Viertel gentrifizieren spürbar, und wer früh da ist, wächst mit. Leipzig-Besonderheit: Die Stadt ist polyzentrisch und fahrradfreundlich; die Kundschaft bleibt gern im eigenen Viertel. Ein Standort in einem wachsenden Kiez schlägt langfristig die teurere Zentrumslage.',
    },
    {
      heading: 'Der Leipzig-Start: günstig, schnell, skalierbar',
      text: 'Bürokratisch ist Leipzig angenehm schlank: Die Gewerbeanmeldung beim Ordnungsamt kostet 25–30 € und läuft online, Friseure tragen sich bei der HWK zu Leipzig in die Handwerksrolle ein, Kosmetik-, Nail- und Lash-Berufe starten zulassungsfrei. Das Gesundheitsamt prüft nach sächsischer Hygieneverordnung — mit dokumentiertem Hygieneplan kein Problem.\n\nDie Kalkulation ist der große Leipzig-Vorteil: Bei 25–45 € Tagesmiete bist du oft schon mit dem zweiten Kunden profitabel. Behandlungspreise liegen aktuell bei 25–35 € (Herren-Cut), 45–65 € (Damen-Cut) und 80–120 € (Volume-Lashes) — Tendenz seit Jahren steigend. Viele Leipziger Selbstständige starten mit zwei bis drei Miettagen pro Woche neben einer Anstellung und skalieren hoch, sobald der Terminkalender es trägt; das Stuhl-Miet-Modell macht genau diesen gleitenden Übergang möglich. Ein Praxis-Tipp für den Aufbau: Leipzigs Szene ist digital gut vernetzt — lokale Instagram-Sichtbarkeit, Kooperationen mit Fotografen aus der Kreativszene (Plagwitz ist voll davon) und Präsenz auf Stadtteil-Events beschleunigen den Kundenstamm-Aufbau hier stärker als klassische Werbung.',
    },
  ],
  dresden: [
    {
      heading: 'Dresden: Ost-Wachstum mit Tech-Kaufkraft',
      text: 'Dresden hat sich still zu einem der spannendsten Beauty-Märkte Ostdeutschlands entwickelt. Der Treiber heißt "Silicon Saxony": Infineon, Globalfoundries, Bosch und die TSMC-Ansiedlung schaffen tausende gut bezahlte Tech-Arbeitsplätze, die TU Dresden liefert konstant junge Zuzügler — und diese Kundschaft gibt für Beauty deutlich mehr aus als der ostdeutsche Durchschnitt. Die Behandlungspreise haben sich westdeutschen Niveaus angenähert, während die Stuhl-Mieten (25–45 €/Tag) günstig geblieben sind. Diese Schere ist die Dresdner Marge.\n\nGleichzeitig ist der Markt noch nicht verteilt: Ketten-Konkurrenz gibt es kaum, spezialisierte Studios für Lashes, PMU oder modernes Barbering sind rar, und wer eine Nische besetzt, wird schnell zur festen Adresse. Dazu kommt ein Faktor, den nur Dresden hat: Millionen Touristen jährlich in der Altstadt, die für Barber-Walk-ins und Styling-Termine ein konstantes Zusatzgeschäft bedeuten. Nach Leipzig ist Dresden der zweite ostdeutsche Markt, in dem sich der frühe Einstieg wirklich lohnt — mit dem Unterschied, dass hier die Tech-Kaufkraft das Wachstum noch planbarer macht.',
    },
    {
      heading: 'Neustadt-Szene und Striesen-Klasse: Standorte in Dresden',
      text: 'Die Äußere Neustadt ist das unangefochtene Szene-Zentrum: Zwischen Alaunstraße, Louisenstraße und Görlitzer Straße drängt sich das jüngste, experimentierfreudigste Publikum der Stadt — Barbershops, Lash-Ateliers und Tattoo-Studios prägen das Bild, und ein neues Konzept spricht sich hier in Wochen herum. Die Mieten liegen am oberen Ende der Stadt, bleiben aber im Bundesvergleich moderat.\n\nStriesen und Blasewitz sind die feinen Adressen: Gründerzeit-Villen, etablierte Kosmetik-Klientel, Termintreue und gehobene Preise — erste Wahl für anspruchsvolle Kosmetik, PMU und Anti-Aging-Behandlungen. Die Innere Altstadt lebt von Touristen- und Einkaufs-Frequenz rund um Prager Straße und Frauenkirche. Pieschen ist Dresdens Aufsteiger-Viertel — noch günstig, zunehmend jung und kreativ — und Löbtau punktet mit Uni-Nähe und niedrigen Einstiegsmieten. Die Standort-Logik: Szene- und Volumen-Geschäft in die Neustadt, Premium-Termingeschäft nach Striesen/Blasewitz, Walk-in-Konzepte in die Altstadt. Die kompakte Stadtstruktur mit gutem Straßenbahn-Netz hält alle Wege kurz.',
    },
    {
      heading: 'Loslegen in Dresden: Formalitäten und Rechnung',
      text: 'Der Start ist unbürokratisch: Gewerbeanmeldung bei der Stadt Dresden für 20–40 €, online möglich. Friseure benötigen den Handwerksrollen-Eintrag bei der HWK Dresden, Kosmetik, Nageldesign und Lashes sind zulassungsfrei. Die sächsische Hygieneverordnung verlangt den üblichen dokumentierten Hygieneplan; bei apparativer Kosmetik gilt bundesweit die NiSV-Fachkunde-Pflicht.\n\nDie Kalkulation spricht für sich: Bei 25–45 € Tagesmiete und Behandlungspreisen von 28–38 € (Herren-Cut), 45–65 € (Damen-Cut) und 90–130 € (Volume-Lashes) trägt sich der Platz ab dem zweiten Kunden, und 100–200 € Tagesgewinn sind gut erreichbar — mit steigender Tendenz, denn die Tech-Gehälter ziehen das Preisniveau Jahr für Jahr nach oben. Zwei Dresden-Tipps: Erstens profitieren englischsprachige Profile überproportional — die internationalen Fachkräfte der Chip-Industrie suchen aktiv Studios, in denen sie sich auf Englisch verständigen können, und werden extrem loyale Stammkunden. Zweitens lohnt der Blick auf den Veranstaltungskalender: Striezelmarkt im Dezember und die Festival-Sommer bringen planbare Frequenz-Spitzen für Styling- und Barber-Angebote in Altstadt-Nähe.',
    },
  ],
  dortmund: [
    {
      heading: 'Dortmund: der Niedrig-Risiko-Einstieg ins Ruhrgebiet',
      text: 'Dortmund ist die größte Stadt des Ruhrgebiets und zugleich einer der günstigsten Großstadt-Märkte Deutschlands für Beauty-Selbstständige: Stuhl-Mieten ab 20 €/Tag bedeuten, dass sich der Platz oft schon mit dem zweiten Kunden trägt. Der Break-even liegt hier so früh wie kaum irgendwo — was Dortmund zum idealen Markt für den Start mit kleinem Budget macht. Gleichzeitig sind die Behandlungspreise nur moderat unter dem Bundesschnitt, die Marge stimmt also.\n\nDer Strukturwandel hat der Stadt eine neue Wirtschaftsbasis gegeben — TU Dortmund, Software-Cluster, Versicherungen, Logistik — und mit ihr eine jüngere, konsumfreudigere Bevölkerung. Die Kundschaft selbst ist typisch Ruhrgebiet: bodenständig, direkt, treu. Wer sich hier einen Namen macht, arbeitet mit einer Stammkunden-Quote, von der Szene-Städte träumen. Und das Einzugsgebiet ist gewaltig: Bochum, Unna, Lünen, Castrop-Rauxel und Hagen liegen in unter 30 Minuten — im Revier pendelt man selbstverständlich für gute Arbeit, Kirchturmdenken gibt es beim Friseurbesuch nicht.',
    },
    {
      heading: 'Kreuzviertel, City, Unionviertel: die Dortmunder Lagen',
      text: 'Das Kreuzviertel ist Dortmunds beliebtestes Ausgeh- und Wohnquartier: Altbau, Cafés, junges akademisches Publikum mit Beauty-Budget — hier funktionieren Barber, Brows und moderne Friseur-Konzepte am besten, zu den höchsten (aber immer noch fairen) Mieten der Stadt. Die City rund um den Westenhellweg gehört zu den frequenzstärksten Einkaufsstraßen Deutschlands und liefert Walk-in-Kundschaft im Minutentakt — ideal für Volumen-Geschäft.\n\nDas Unionviertel rund um das Dortmunder U entwickelt sich mit der Kreativwirtschaft zum spannendsten Aufsteiger-Standort, das Kaiserviertel ist die etablierte gute Adresse im Osten mit gehobener Wohn-Klientel. Hörde am Phoenix-See hat sich vom Stahlstandort zum Naherholungs- und Neubau-Quartier gewandelt — die Neubau-Bewohner bringen Kaufkraft mit, und die Studio-Dichte ist noch niedrig. Körne und die weiteren Stadtteile bieten den günstigsten Einstieg für nachbarschaftliches Termingeschäft. Dortmund-Logik: Die Stadt ist preissensibler als Rhein-Metropolen, aber loyal — wer faire Preise mit sichtbarer Qualität kombiniert, füllt seinen Kalender über Empfehlungen schneller als über jede Lage.',
    },
    {
      heading: 'Rechnung und Start: Dortmund praktisch',
      text: 'Die Formalitäten sind schnell erledigt: Gewerbeanmeldung beim Ordnungsamt Dortmund (ca. 26 €, online möglich), Handwerksrollen-Eintrag für Friseure bei der HWK Dortmund, zulassungsfreier Start für Kosmetik, Nails und Lashes. Die Hygiene-Standards entsprechen NRW-Niveau — Hygieneplan führen, Instrumente VAH-konform aufbereiten, fertig.\n\nDie Dortmund-Rechnung ist die einfachste unter den Großstädten: 20–40 € Tagesmiete gegen Behandlungspreise von 22–32 € (Herren-Cut), 40–60 € (Damen-Cut) und 80–110 € (Volume-Lashes). Ab dem dritten Kunden ist praktisch alles Gewinn; 100–180 € Tagesgewinn sind solide erreichbar, im Kreuzviertel mit Premium-Positionierung mehr. Zwei Dortmund-spezifische Hebel: Erstens der BVB — an Heimspiel-Wochenenden strömen über 80.000 Menschen durch die Stadt, und Barber-Angebote in City- und Kreuzviertel-Lage spüren die Frequenz deutlich. Zweitens die Studierenden: TU und FH bringen über 50.000 junge Menschen, deren Preisbewusstsein sich mit Volumen-Modellen (schnelle, standardisierte Cuts mit hoher Taktung) hervorragend bedienen lässt — und die nach dem Abschluss als besser verdienende Stammkunden bleiben.',
    },
  ],
  essen: [
    {
      heading: 'Essen: die Rü als Beauty-Meile des Reviers',
      text: 'Essen hat, was im Ruhrgebiet selten ist: eine echte Flanier- und Beauty-Meile. Die Rüttenscheider Straße — die "Rü" — reiht auf zwei Kilometern Gastronomie, inhabergeführten Einzelhandel und die höchste Dichte an Friseuren, Barbershops, Nail- und Kosmetikstudios der Region aneinander. Wer hier einen Stuhl mietet, kauft sich in eine gewachsene Laufkundschaft ein, für die man anderswo Jahre Marketing bräuchte. Entsprechend liegen die Rü-Mieten am oberen Ende der Stadt — und sind es wert.\n\nAbseits von Rüttenscheid ist Essen ein klassischer günstiger Revier-Markt: In Frohnhausen, Holsterhausen oder Steele beginnt die Stuhl-Miete bei 20 €/Tag, die Kundschaft ist treu und unkompliziert. Die Stadt profitiert von ihrer Rolle als Konzern-Standort (RWE, Evonik, Aldi Nord, thyssenkrupp in Sichtweite) und vom Universitätsklinikum, das Holsterhausen zu einem interessanten Standort für medizinische Fußpflege und Kosmetik macht. Diese Bandbreite — Premium-Meile und günstige Stadtteile in einer Stadt — macht Essen flexibler als die meisten Revier-Nachbarn.',
    },
    {
      heading: 'Standort-Wahl in Essen: Rü oder Stadtteil?',
      text: 'Die Grundsatzfrage in Essen lautet: Rüttenscheid oder nicht? Die Rü und das angrenzende Südviertel liefern Sichtbarkeit, Laufkundschaft und ein ausgeh-freudiges Publikum mit Beauty-Budget — dafür zahlst du 35–45 €/Tag und konkurrierst mit der dichtesten Studio-Landschaft der Stadt. Wer eine klare Spezialisierung mitbringt (Balayage, Skin Fades, Volume-Lashes), setzt sich hier trotzdem schnell durch, denn die Frequenz verzeiht auch mal eine ruhige Woche.\n\nDie Alternative sind die Stadtteile: Holsterhausen mit Uniklinik-Nähe (Klinik-Personal bucht verlässlich und empfiehlt intern weiter), das bürgerliche Borbeck, das günstige Frohnhausen und Steele mit eigenem Zentrum im Osten. Kettwig an der Ruhr ist der Premium-Ausreißer im Süden — fast schon Bergisches Idyll, mit kaufkräftiger älterer Klientel für gehobene Kosmetik. Praktisch bewährt hat sich in Essen das Kombi-Modell: zwei bis drei feste Tage im günstigen Stadtteil für die Stammkundschaft, dazu ein flexibler Rü-Tag für Neukunden-Gewinnung und Sichtbarkeit. Die tageweise Stuhl-Miete macht genau solche Mischstrategien möglich, ohne doppelte Fixkosten zu schultern.',
    },
    {
      heading: 'Essen praktisch: Anmeldung, Hygiene, Kalkulation',
      text: 'Die Anmeldung folgt dem NRW-Standard: Gewerbeanmeldung beim Essener Ordnungsamt (ca. 26 €), Handwerksrolle für Friseure über die HWK Düsseldorf, zulassungsfreier Start für Kosmetik, Nageldesign und Lashes. Das Essener Gesundheitsamt achtet besonders bei Nageldesign auf Staub-Absaugung und Instrumenten-Hygiene — ein sauber geführter Hygieneplan ist Pflicht und bei Kontrollen die halbe Miete.\n\nKalkulatorisch gehört Essen zu den dankbarsten Märkten: 20–45 € Tagesmiete gegen Behandlungspreise, die in Rüttenscheid fast westdeutsches Großstadt-Niveau erreichen (Damen-Cut 45–65 €, Gesichtsbehandlung 55–80 €). Der Break-even liegt beim zweiten bis dritten Kunden, 100–200 € Tagesgewinn sind realistisch. Ein unterschätzter Essen-Hebel ist die Messe Essen: Ausgerechnet hier finden mit der Motorshow und weiteren Publikumsmessen frequenzstarke Events statt, und auch die Grugahalle bringt Veranstaltungs-Publikum in Rü-Nähe. Wer an solchen Wochenenden Zusatztage bucht, nimmt spürbare Umsatz-Spitzen mit. Und für medizinnahe Angebote gilt: Die Nähe zum Uniklinikum ist ein Standortvorteil, den bisher erstaunlich wenige Anbieter systematisch nutzen.',
    },
  ],
  bremen: [
    {
      heading: 'Bremen: entspannt selbstständig im hanseatischen Markt',
      text: 'Bremen ist der Markt für alle, die Selbstständigkeit ohne Metropol-Stress suchen. Die Hansestadt kombiniert niedrige Fixkosten (Stuhl-Miete ab 30 €/Tag), moderaten Konkurrenzdruck und eine Kundschaft, die hanseatisch tickt: zurückhaltend beim ersten Kontakt, dann aber jahrzehntetreu. Preis-Hopping und ständiges Anbieter-Wechseln sind hier unüblich — wer überzeugt, hat seine Kundschaft sicher.\n\nAuffällig ist die Bremer Work-Life-Balance-Kultur: Überdurchschnittlich viele Beauty-Profis arbeiten hier bewusst an drei oder vier Tagen pro Woche und kombinieren Selbstständigkeit mit Familie oder Zweitprojekten. Das Stuhl-Miet-Modell passt perfekt zu dieser Arbeitsweise — flexible 2-, 3- und 4-Tage-Modelle sind in Bremen verbreiteter als fast überall sonst, und Salon-Betreiber sind entsprechend offen für Teilzeit-Arrangements. Wirtschaftlich trägt die Stadt breiter, als ihr Ruf vermuten lässt: Airbus, Mercedes, OHB, der Hafen und eine wachsende Digital-Szene in der Überseestadt sorgen für stabile Einkommen und verlässliche Beauty-Budgets.',
    },
    {
      heading: 'Viertel, Schwachhausen, Überseestadt: Bremens Lagen',
      text: 'Das Viertel (Ostertor/Steintor) ist Bremens kreatives Herz — die dichteste Studio-Szene der Stadt, ein junges, beauty-affines Publikum und Laufkundschaft entlang des Ostertorsteinwegs. Barber, Lash und ausgefallene Konzepte finden hier ihr Publikum; die Mieten liegen am oberen Ende der (moderaten) Bremer Spanne. Schwachhausen dahinter ist die feine Adresse: Altbremer Häuser, kaufkräftige Klientel, ideale Bedingungen für gehobene Kosmetik und etablierte Friseur-Konzepte mit Termingeschäft.\n\nFindorff ist der familiäre Allrounder mit Wochenmarkt-Kultur und treuer Nachbarschafts-Kundschaft, die Neustadt links der Weser das Aufsteiger-Quartier mit jungem Zuzug und noch günstigen Plätzen. Die Überseestadt schließlich wächst als Büro- und Neubau-Quartier — hier bucht Büro-Publikum in Mittagspause und Feierabend, und die Studio-Dichte ist noch gering. Nicht zu vergessen die Innenstadt (Mitte) mit Einkaufs-Laufkundschaft rund um Obernstraße und Sögestraße. Und: Das Einzugsgebiet reicht weit ins Umland — aus Delmenhorst, Achim, Lilienthal und Stuhr kommt Kundschaft regelmäßig in die Stadt, denn spezialisierte Studios gibt es dort kaum.',
    },
    {
      heading: 'Der Bremer Weg: Teilzeit-Modelle und solide Rechnung',
      text: 'Bürokratisch ist Bremen unkompliziert: Die Gewerbeanmeldung läuft über das Serviceportal der Stadt (rund 30 €), Friseure tragen sich bei der Handwerkskammer Bremen ein, Kosmetik-, Nail- und Lash-Berufe starten zulassungsfrei. Die Hygiene-Anforderungen des Gesundheitsamts Bremen entsprechen dem Nord-Standard — dokumentierter Hygieneplan, VAH-konforme Desinfektion.\n\nDie Kalkulation ist entspannt: Bei 30–50 € Tagesmiete und Behandlungspreisen von 25–35 € (Herren-Cut), 42–60 € (Damen-Cut) und 85–115 € (Volume-Lashes) trägt sich der Platz ab dem zweiten Kunden. 90–160 € Tagesgewinn sind die realistische Mitte — bewusst konservativ gerechnet, denn viele Bremer Profis optimieren nicht auf Maximum, sondern auf Planbarkeit. Genau darin liegt der Bremer Praxis-Tipp: Nutze die verbreiteten Teilzeit-Modelle strategisch. Ein 3-Tage-Paket mit Rabatt als Basis, kombiniert mit saisonalen Zusatztagen (Weihnachtsgeschäft, Abiball- und Hochzeits-Saison von Mai bis September), ergibt eine Auslastung, die zum Leben passt statt umgekehrt. Und baue auf den Wochenmarkt-Effekt: In Findorff und im Viertel läuft Neukunden-Gewinnung über Nachbarschafts-Präsenz und Empfehlung deutlich besser als über Anzeigen.',
    },
  ],
}

/** Guide-Sektionen für eine Stadt — leeres Array wenn (noch) keine vorhanden. */
export function getCityGuide(slug: string): GuideSection[] {
  return CITY_GUIDES[slug] ?? []
}
